import type { StarterSubject } from "../types.js";

const NMC = "https://www.nmc.org.in/";
const NBE = "https://natboard.edu.in/";
const MOHFW = "https://mohfw.gov.in/";
const NHM = "https://www.nhm.gov.in/";
const TBC = "https://tbcindia.gov.in/";

export const NEETPG_PRECLINICAL: StarterSubject = {
  slug: "neet-pg-preclinical",
  name: "Pre & Para-clinical Sciences",
  description: "Pathology, pharmacology, microbiology and biochemistry at the depth NEET PG single-best-answer questions actually test.",
  topics: [
    {
      slug: "pathology",
      title: "Pathology",
      articles: [
        {
          slug: "cell-injury-and-cell-death",
          title: "Cell Injury, Necrosis and Apoptosis: Mechanisms and Patterns",
          syllabusAnchor: "NEET PG — Pathology: cell injury, cellular adaptation and cell death.",
          mustCover: [
            "Cellular adaptations — hypertrophy, hyperplasia, atrophy and metaplasia — and the stimulus that drives each",
            "Reversible injury: cellular swelling and fatty change, and why the cell can still recover",
            "ATP depletion as the central event: sodium-potassium pump failure, a shift to anaerobic glycolysis, and ribosomal detachment",
            "The point of no return: irreversible membrane damage and mitochondrial permeability transition",
            "Free radical injury and the added damage of ischaemia-reperfusion",
            "Nuclear morphology of necrosis: pyknosis, karyorrhexis and karyolysis",
            "The types of necrosis with their classic associations — coagulative in ischaemic infarcts of most solid organs, liquefactive in brain infarcts and abscesses, caseous in tuberculosis, fat necrosis in acute pancreatitis, fibrinoid in immune vasculitis, and gangrenous necrosis in limb ischaemia",
            "Apoptosis: the intrinsic mitochondrial pathway with Bcl-2 family regulation and cytochrome c release, and the extrinsic death receptor pathway, both converging on executioner caspases",
            "Necrosis versus apoptosis on the discriminating features: membrane integrity, energy requirement, surrounding inflammation, and whether the process is physiological",
          ],
          worked: ["Reason from blood supply and tissue architecture why a myocardial infarct shows coagulative necrosis while a cerebral infarct shows liquefactive necrosis"],
          traps: [
            "Calling all cell swelling irreversible — hydropic change is recoverable until membrane integrity is lost",
            "Assuming apoptosis provokes inflammation; it does not, which is why it is the mechanism of physiological cell loss",
            "Confusing caseous with coagulative necrosis because both are eosinophilic — the granulomatous background is the discriminator",
          ],
          officialSources: [NMC],
          diagram: "compare",
          keywords: ["types of necrosis NEET PG", "apoptosis intrinsic extrinsic pathway", "reversible vs irreversible cell injury", "cellular adaptation pathology"],
          order: 0,
        },
        {
          slug: "inflammation-repair-and-neoplasia",
          title: "Inflammation, Repair and Neoplasia: General Pathology Core",
          syllabusAnchor: "NEET PG — Pathology: acute and chronic inflammation, repair, and neoplasia.",
          mustCover: [
            "Vascular events of acute inflammation: transient vasoconstriction, vasodilatation, increased permeability and stasis, and why the fluid is an exudate",
            "Cellular events in sequence: margination, selectin-mediated rolling, integrin-mediated firm adhesion, transmigration and chemotaxis",
            "Chemical mediators grouped by source and action — vasoactive amines, arachidonic acid metabolites through the cyclooxygenase and lipoxygenase routes, cytokines, complement and kinins",
            "Outcomes of acute inflammation: complete resolution, abscess formation, fibrosis, or progression to chronic inflammation",
            "Chronic inflammation: the mononuclear infiltrate, and granuloma formation with epithelioid cells and giant cells, split into caseating and non-caseating patterns",
            "Repair: labile, stable and permanent cell populations, granulation tissue, and healing by primary versus secondary intention",
            "Factors that delay healing, and the abnormal outcomes — keloid, hypertrophic scar and contracture",
            "Neoplasia: the hallmarks of cancer, and benign versus malignant lesions compared on differentiation, growth rate, local invasion and metastasis",
            "Grading as degree of differentiation versus staging as anatomic extent, and the real role of tumour markers — monitoring response and detecting recurrence rather than making the diagnosis",
          ],
          worked: ["Trace a full-thickness skin wound from haemostasis through inflammation, proliferation and remodelling, naming the dominant cell type in each phase"],
          traps: [
            "Using tumour markers as diagnostic tests when their exam-relevant role is follow-up and monitoring",
            "Interchanging grading and staging — staging usually carries the stronger prognostic weight",
            "Assuming every granuloma is tuberculous instead of asking whether it caseates",
          ],
          officialSources: [NMC],
          diagram: "flow",
          keywords: ["acute inflammation mediators", "granuloma formation pathology", "grading vs staging cancer", "hallmarks of cancer NEET PG"],
          order: 1,
        },
      ],
    },
    {
      slug: "pharmacology",
      title: "Pharmacology",
      articles: [
        {
          slug: "general-and-autonomic-pharmacology",
          title: "General and Autonomic Pharmacology: Kinetics, Dynamics, Receptors",
          syllabusAnchor: "NEET PG — Pharmacology: general pharmacology and autonomic nervous system drugs.",
          mustCover: [
            "Absorption and bioavailability, the first-pass effect, and how the route of administration changes both",
            "Distribution: volume of distribution as a proportionality constant, plasma protein binding, and displacement interactions",
            "Metabolism: phase I reactions such as oxidation, reduction and hydrolysis largely through cytochrome P450, versus phase II conjugation, plus enzyme induction and inhibition",
            "Clearance, half-life and steady state: why several half-lives are needed to reach or wash out steady state, and when a loading dose is justified",
            "First-order versus zero-order elimination, and why saturable kinetics make toxicity unpredictable",
            "Pharmacodynamics read off dose-response curves: full agonist, partial agonist, inverse agonist, and competitive versus non-competitive antagonist",
            "Potency versus efficacy, the meaning of ED50 and LD50, and the therapeutic index as a margin-of-safety measure",
            "The autonomic receptor map — muscarinic and nicotinic cholinergic receptors, and alpha-1, alpha-2, beta-1 and beta-2 adrenergic receptors — with the dominant organ response of each",
            "Autonomic drug classes and the toxidromes they produce, including cholinergic excess in organophosphate poisoning and the anticholinergic syndrome",
          ],
          worked: ["Read a pair of dose-response curves and decide whether the second drug is a competitive antagonist, a non-competitive antagonist or a partial agonist"],
          traps: [
            "Confusing potency with efficacy — a rightward shift is potency, a lowered plateau is efficacy",
            "Expecting a competitive antagonist to reduce the maximal response; it is surmountable and shifts the curve instead",
            "Treating half-life as a fixed drug property when it depends on both clearance and volume of distribution",
          ],
          officialSources: [NMC],
          diagram: "compare",
          keywords: ["pharmacokinetics NEET PG", "agonist vs antagonist dose response", "therapeutic index pharmacology", "autonomic receptors drugs"],
          order: 0,
        },
        {
          slug: "antimicrobial-pharmacology-and-toxicity",
          title: "Antimicrobials: Mechanism Classes, Resistance and Toxicity",
          syllabusAnchor: "NEET PG — Pharmacology: chemotherapy of microbial diseases.",
          mustCover: [
            "The mechanism classes: cell wall synthesis inhibitors, protein synthesis inhibitors acting at the 30S and 50S subunits, nucleic acid synthesis inhibitors, and folate pathway inhibitors",
            "Beta-lactams in order — penicillins, cephalosporins by generation, carbapenems and monobactams — and what a beta-lactamase inhibitor adds to the combination",
            "Bactericidal versus bacteriostatic agents, and concentration-dependent versus time-dependent killing",
            "Resistance mechanisms: enzymatic inactivation, target modification, reduced permeability and efflux pumps, with MRSA and ESBL producers as worked examples",
            "Aminoglycosides: the characteristic nephrotoxicity and ototoxicity, and the dosing strategy that follows from concentration-dependent killing",
            "Vancomycin: spectrum, the infusion-related reaction, and the monitoring it requires",
            "First-line antitubercular drugs and their characteristic adverse effects — hepatotoxicity, peripheral neuropathy with isoniazid, optic neuritis with ethambutol, hyperuricaemia with pyrazinamide, and orange discolouration plus enzyme induction with rifampicin",
            "Why tuberculosis needs multi-drug fixed-duration regimens, and what drug resistance changes about the regimen",
            "Prophylactic versus empirical versus definitive therapy, and the logic of antimicrobial stewardship",
          ],
          worked: ["Match a set of characteristic adverse effects back to the responsible antitubercular drug and state the monitoring that follows from each"],
          traps: [
            "Stopping rifampicin for orange discolouration of secretions, which is expected and harmless",
            "Assuming later cephalosporin generations simply add cover without losing any gram-positive activity",
          ],
          officialSources: [NMC, TBC],
          diagram: "hierarchy",
          keywords: ["antimicrobial mechanism of action", "antibiotic resistance NEET PG", "aminoglycoside toxicity", "antitubercular drug side effects"],
          order: 1,
        },
      ],
    },
    {
      slug: "microbiology-and-biochemistry",
      title: "Microbiology & Biochemistry",
      articles: [
        {
          slug: "immunity-hypersensitivity-and-metabolic-disorders",
          title: "Immunity, Hypersensitivity and Inborn Errors of Metabolism",
          syllabusAnchor: "NEET PG — Microbiology and Biochemistry: sterilisation, immunity and metabolic disorders.",
          mustCover: [
            "Sterilisation versus disinfection versus antisepsis, with the physical and chemical methods matched to their standard indications",
            "Autoclaving, and the chemical and biological indicators used to confirm that a cycle worked",
            "Innate immunity: barriers, phagocytes, natural killer cells and complement, and the absence of memory",
            "Adaptive immunity: humoral and cell-mediated arms, antigen presentation on MHC class I versus class II, and immunological memory",
            "Immunoglobulin classes and the distinguishing role of each in infection and allergy",
            "Type I hypersensitivity: IgE-mediated mast cell degranulation, with anaphylaxis and atopy as the classic examples",
            "Types II, III and IV: antibody-mediated cytotoxicity as in autoimmune haemolytic anaemia, immune complex deposition as in serum sickness, and delayed T-cell mediated reactions as in the tuberculin test and contact dermatitis",
            "Core metabolic pathways and their cellular location: glycolysis, the citric acid cycle, oxidative phosphorylation, gluconeogenesis and the urea cycle",
            "Inborn errors of metabolism as a category — enzyme deficiency leading to substrate accumulation and product deficiency — and why newborn screening exists",
          ],
          worked: ["Classify an illustrative reaction as type I to IV by asking which effector is responsible and how quickly the reaction appeared"],
          traps: [
            "Calling the tuberculin reaction antibody-mediated when it is a delayed T-cell response",
            "Using sterilisation and disinfection interchangeably — only sterilisation reliably removes spores",
          ],
          officialSources: [NMC],
          diagram: "hierarchy",
          keywords: ["hypersensitivity types examples", "innate vs adaptive immunity", "sterilisation and disinfection methods", "inborn errors of metabolism NEET PG"],
          order: 0,
        },
      ],
    },
  ],
};

export const NEETPG_MEDICINE: StarterSubject = {
  slug: "neet-pg-medicine",
  name: "Medicine & Allied",
  description: "Internal medicine reasoning built around interpretation, discriminating signs and the stepwise approach a vignette rewards.",
  topics: [
    {
      slug: "internal-medicine",
      title: "Internal Medicine",
      articles: [
        {
          slug: "acid-base-and-electrolyte-disorders",
          title: "Acid-Base and Electrolytes: A Stepwise ABG Approach",
          syllabusAnchor: "NEET PG — General Medicine: fluid, electrolyte and acid-base disturbances.",
          mustCover: [
            "The Henderson-Hasselbalch relationship and what each measured ABG variable actually represents",
            "A fixed interpretation order: read the pH, name the primary disorder, test whether compensation is appropriate, then calculate the anion gap",
            "The anion gap, its correction for albumin, and the delta-delta ratio used to unmask a second disorder",
            "High anion gap versus normal anion gap (hyperchloraemic) metabolic acidosis, including renal tubular acidosis and gastrointestinal bicarbonate loss",
            "Metabolic alkalosis split into chloride-responsive and chloride-resistant causes",
            "Respiratory acidosis and alkalosis, and how acute compensation differs from established chronic renal compensation",
            "Mixed disorders, and the two checks that expose them — inadequate or excessive compensation, and a delta-delta mismatch",
            "Hyponatraemia assessed by tonicity and volume status, and why the rate of correction matters",
            "Hyperkalaemia: the ECG progression, and the three-step management principle of stabilising the membrane, shifting potassium into cells, then removing it from the body",
          ],
          worked: ["Interpret an illustrative set of ABG values step by step through pH, primary disorder, expected compensation and anion gap to a single final diagnosis"],
          traps: [
            "Naming the disorder from bicarbonate alone before reading pH and pCO2 together",
            "Forgetting to correct the anion gap in hypoalbuminaemia, which hides a genuine gap acidosis",
            "Reporting appropriate compensation as though it were a second primary disorder",
          ],
          officialSources: [NMC, NBE],
          diagram: "flow",
          keywords: ["ABG interpretation NEET PG", "anion gap metabolic acidosis", "delta delta ratio", "hyperkalaemia management steps"],
          order: 0,
        },
        {
          slug: "cardiology-and-endocrine-essentials",
          title: "Cardiology and Endocrine Essentials: ECG, Murmurs, TFT Patterns",
          syllabusAnchor: "NEET PG — General Medicine: cardiovascular system and endocrinology.",
          mustCover: [
            "A reproducible ECG reading order: rate, rhythm, axis, intervals, chamber enlargement, then ST-segment and T-wave changes",
            "The recurring exam tracings: ischaemic ST-T patterns with their anatomical territories, atrial fibrillation, and the degrees of atrioventricular block",
            "Systolic versus diastolic murmurs, site of maximal intensity, and radiation as the first localising clues",
            "Bedside manoeuvres that separate murmurs — respiration, Valsalva, handgrip and squatting — explained through their effect on preload and afterload",
            "Heart failure classified by ejection fraction, by NYHA functional class, and as acute versus chronic decompensation",
            "Thyroid function test patterns read from the TSH and free T4 pair: primary hypothyroidism, subclinical disease, primary hyperthyroidism and central patterns",
            "The diagnostic criteria for diabetes mellitus as a concept — fasting plasma glucose, the oral glucose tolerance test, HbA1c and a symptomatic random value — and the requirement for confirmation",
            "Diabetic ketoacidosis versus hyperosmolar hyperglycaemic state on the discriminating clinical and biochemical features",
            "Adrenal insufficiency: the direction cortisol and ACTH move in primary versus secondary disease, and the pigmentation clue that follows",
          ],
          worked: ["Take a TSH and free T4 pair and reason to primary, subclinical or central thyroid disease, then name the next investigation"],
          traps: [
            "Calling every raised TSH overt hypothyroidism without checking free T4",
            "Expecting most murmurs to become louder with Valsalva when reduced preload softens them",
            "Diagnosing diabetes on a single abnormal value in an asymptomatic person",
          ],
          officialSources: [NMC, MOHFW],
          diagram: "compare",
          keywords: ["ECG interpretation NEET PG", "murmur manoeuvres handgrip valsalva", "thyroid function test patterns", "DKA vs HHS"],
          order: 1,
        },
      ],
    },
    {
      slug: "clinical-approach",
      title: "Clinical Approach",
      articles: [
        {
          slug: "approach-to-chest-pain-breathlessness-and-fever",
          title: "Approach to Chest Pain, Breathlessness and Fever",
          syllabusAnchor: "NEET PG — Clinical Medicine: approach to common presenting complaints.",
          mustCover: [
            "The shape of every diagnostic algorithm: stabilise first, exclude the immediately life-threatening causes, narrow by history and examination, then confirm with a targeted investigation",
            "Chest pain: separating cardiac, aortic, pulmonary, gastrointestinal and musculoskeletal causes on character, radiation, duration and aggravating factors",
            "The early investigations that change management in acute chest pain, and what a single normal early result does not exclude",
            "Breathlessness worked through an airway, parenchymal, pulmonary vascular, cardiac and non-cardiorespiratory framework",
            "Bedside discriminators between cardiac and respiratory breathlessness: orthopnoea, paroxysmal nocturnal dyspnoea, wheeze, and the jugular venous pressure",
            "Fever: duration-based thinking, localising symptoms, and the point at which a fever meets the definition of pyrexia of unknown origin",
            "The red flags in each presentation that force immediate escalation rather than further history",
            "How a vignette hides the answer: usually one history detail or one examination sign is the discriminator, and the rest is distractor",
          ],
          worked: ["Work a chest pain vignette from initial stabilisation to a single most likely diagnosis, naming the discriminator used at each branch"],
          traps: [
            "Ordering investigations before stabilising the patient in an emergency vignette",
            "Excluding a diagnosis on one normal early test when serial testing is the standard",
          ],
          officialSources: [NMC, NBE],
          diagram: "flow",
          keywords: ["approach to chest pain", "dyspnoea differential diagnosis", "pyrexia of unknown origin approach", "clinical vignette NEET PG"],
          order: 0,
        },
      ],
    },
  ],
};

export const NEETPG_CLINICAL: StarterSubject = {
  slug: "neet-pg-clinical",
  name: "Surgery, Obstetrics & Paediatrics",
  description: "Clinical subjects revised as algorithms — resuscitate, classify, then act — the way single-best-answer stems are written.",
  topics: [
    {
      slug: "surgery",
      title: "Surgery",
      articles: [
        {
          slug: "trauma-primary-survey-and-shock",
          title: "Trauma: The Primary Survey and Shock Classification",
          syllabusAnchor: "NEET PG — Surgery: trauma, resuscitation and shock.",
          mustCover: [
            "The primary survey in its fixed order — airway with cervical spine control, breathing, circulation, disability, exposure — and why the order cannot be rearranged",
            "Airway assessment with cervical spine protection, and the immediately life-threatening chest injuries identified at the breathing step",
            "Circulation: control of external haemorrhage, vascular access, and the anatomical sites where large volumes of blood can be concealed",
            "The disability assessment and the three components of the Glasgow Coma Scale",
            "Adjuncts to the primary survey, and where focused ultrasound and radiographs fit without delaying resuscitation",
            "The secondary survey as a head-to-toe examination performed only once the primary survey problems are corrected",
            "Shock classified by mechanism — hypovolaemic, cardiogenic, obstructive and distributive — with the haemodynamic profile that separates them",
            "The four classes of haemorrhagic shock, which vital sign changes first in each, and why blood pressure is a late and misleading indicator",
            "Damage control resuscitation: balanced blood product transfusion, early haemorrhage control, and avoiding the lethal triad of hypothermia, acidosis and coagulopathy",
          ],
          worked: ["Take an illustrative set of trauma vital signs, classify the haemorrhagic shock class, and state the next step in the primary survey"],
          traps: [
            "Waiting for hypotension to diagnose shock when tachycardia and a narrowed pulse pressure appear earlier",
            "Starting the secondary survey while an airway, breathing or circulation problem is unresolved",
            "Treating a normal initial haemoglobin as evidence against significant acute haemorrhage",
          ],
          officialSources: [NMC],
          diagram: "flow",
          keywords: ["trauma primary survey ABCDE", "classes of haemorrhagic shock", "types of shock comparison", "damage control resuscitation"],
          order: 0,
        },
        {
          slug: "acute-abdomen-wound-healing-and-surgical-infection",
          title: "Acute Abdomen, Wound Healing and Surgical Site Infection",
          syllabusAnchor: "NEET PG — Surgery: acute abdomen, wound healing and surgical infection.",
          mustCover: [
            "The phases of wound healing — haemostasis, inflammation, proliferation and remodelling — with the dominant cell type in each",
            "Healing by primary, secondary and tertiary intention, and the wound characteristics that decide which is chosen",
            "Local and systemic factors that delay healing, and the abnormal scars that result",
            "Surgical wound classification from clean to dirty, and how the class predicts infection risk",
            "Surgical site infection: risk factors, the prevention bundle including correct timing of prophylaxis relative to incision, and recognition of an established infection",
            "The acute abdomen: pain character, migration and peritoneal signs as the first discriminators",
            "Right iliac fossa pain differentials, and the signs classically described in appendicitis",
            "Upper abdominal differentials separated on their discriminating features: perforated peptic ulcer, acute cholecystitis with Murphy's sign, and acute pancreatitis",
            "Intestinal obstruction versus perforation on clinical presentation and erect abdominal radiograph findings",
          ],
          worked: ["Reason through a right iliac fossa pain vignette, using the discriminating sign for each differential to reach one diagnosis"],
          traps: [
            "Observing a rigid, silent abdomen instead of treating it as a surgical emergency",
            "Giving antibiotic prophylaxis at the wrong time relative to incision and still calling it prevention",
          ],
          officialSources: [NMC],
          diagram: "compare",
          keywords: ["acute abdomen differential diagnosis", "phases of wound healing", "surgical site infection prevention", "appendicitis clinical signs"],
          order: 1,
        },
      ],
    },
    {
      slug: "obstetrics-gynaecology",
      title: "Obstetrics & Gynaecology",
      articles: [
        {
          slug: "antenatal-care-and-normal-labour",
          title: "Antenatal Care, Normal Labour and the Partograph",
          syllabusAnchor: "NEET PG — Obstetrics: antenatal care, normal labour and monitoring.",
          mustCover: [
            "The purpose of the antenatal visit schedule and how the content of a visit changes as pregnancy advances",
            "The routine antenatal investigations and what each one is screening for",
            "Antenatal supplementation and immunisation as delivered under the national programme, with the counselling that accompanies them",
            "The danger signs a pregnant woman must be told to report immediately",
            "The three stages of labour, and what marks the beginning and end of each",
            "The cardinal movements of normal labour as an ordered mechanical sequence",
            "The partograph: what is plotted on it, and what crossing the alert line and the action line means for management",
            "Assessment of progress in labour: cervical dilatation, descent, uterine contractions and fetal heart rate monitoring",
          ],
          worked: ["Read an illustrative partograph and decide whether labour is progressing normally, has crossed the alert line, or needs escalation"],
          traps: [
            "Using the partograph as a record of what happened rather than a decision tool",
            "Judging delay without first deciding whether labour is in the latent or the active phase",
          ],
          officialSources: [MOHFW, NHM],
          diagram: "timeline",
          keywords: ["antenatal care schedule India", "stages of labour", "partograph interpretation", "cardinal movements of labour"],
          order: 0,
        },
        {
          slug: "obstetric-emergencies-haemorrhage-and-hypertension",
          title: "Obstetric Emergencies: Postpartum Haemorrhage and Hypertension",
          syllabusAnchor: "NEET PG — Obstetrics: obstetric emergencies and hypertensive disorders of pregnancy.",
          mustCover: [
            "Postpartum haemorrhage split into primary and secondary by timing, and why visual estimation of blood loss is unreliable",
            "The tone, trauma, tissue and thrombin framework, with the clinical clue that points to each cause",
            "Uterine atony as the commonest cause, and the stepwise response — call for help, uterine massage, uterotonics, then examination for genital tract trauma and retained tissue",
            "Escalation when medical measures fail: intrauterine tamponade, compression sutures, stepwise devascularisation and hysterectomy as the final step",
            "Risk factors that allow anticipation, and active management of the third stage as prevention",
            "Hypertensive disorders of pregnancy classified as chronic hypertension, gestational hypertension, pre-eclampsia, eclampsia, and pre-eclampsia superimposed on chronic hypertension",
            "The features that define severe disease, and the end-organ involvement they reflect",
            "Management principles: blood pressure control, seizure prophylaxis with magnesium sulphate, monitoring for toxicity, and delivery as the definitive treatment",
            "Eclampsia: the immediate priorities of airway protection, seizure control and prevention of recurrence before planning delivery",
          ],
          worked: ["Work a postpartum haemorrhage vignette through the tone, trauma, tissue and thrombin framework to the specific intervention required next"],
          traps: [
            "Reaching for surgical measures before uterine massage and uterotonics in atonic haemorrhage",
            "Insisting on proteinuria for a diagnosis of pre-eclampsia when end-organ features can establish it",
            "Assuming delivery ends the risk of eclampsia, when seizures can occur postpartum",
          ],
          officialSources: [MOHFW, NHM],
          diagram: "flow",
          keywords: ["postpartum haemorrhage management", "four T causes of PPH", "hypertensive disorders of pregnancy", "eclampsia magnesium sulphate"],
          order: 1,
        },
      ],
    },
    {
      slug: "paediatrics",
      title: "Paediatrics",
      articles: [
        {
          slug: "neonatal-resuscitation-and-child-health-framework",
          title: "Neonatal Resuscitation, Milestones and Immunisation",
          syllabusAnchor: "NEET PG — Paediatrics: newborn care, growth and development, and immunisation.",
          mustCover: [
            "The rapid assessment at birth that decides whether a newborn needs resuscitation or routine care with the mother",
            "The initial steps within the first minute: warmth, positioning, clearing the airway only if required, drying and stimulation",
            "Escalation in order: effective positive pressure ventilation, heart rate as the primary indicator of response, then chest compressions, with medication as the last step",
            "Post-resuscitation care, and the reasoning behind not initiating or discontinuing resuscitation",
            "Growth assessment: weight, length and head circumference plotted on growth charts, and what crossing centiles signifies",
            "Developmental milestones across the gross motor, fine motor, language and social domains, learnt as parallel sequences rather than isolated facts",
            "Red-flag developmental delay and why a lost milestone is more serious than a late one",
            "The structure of the Universal Immunisation Programme: vaccines given at birth, during infancy and as boosters, with the route of administration for each, and the true versus false contraindications",
          ],
          worked: ["Work through a non-vigorous newborn step by step, naming the assessment that triggers each escalation"],
          traps: [
            "Judging the response to resuscitation by colour instead of heart rate",
            "Treating minor illness as a contraindication to routine immunisation and creating a missed opportunity",
          ],
          officialSources: [MOHFW, NHM],
          diagram: "flow",
          keywords: ["neonatal resuscitation algorithm", "developmental milestones paediatrics", "universal immunisation programme schedule", "growth chart interpretation"],
          order: 0,
        },
      ],
    },
  ],
};

export const NEETPG_COMMUNITY_STRATEGY: StarterSubject = {
  slug: "neet-pg-community-and-strategy",
  name: "Community Medicine & Exam Strategy",
  description: "Epidemiology and biostatistics as they are actually asked, plus a preparation method built on recall and test analysis.",
  topics: [
    {
      slug: "community-medicine",
      title: "Community Medicine",
      articles: [
        {
          slug: "epidemiology-and-biostatistics-essentials",
          title: "Epidemiology Essentials: Study Designs, Bias and Screening",
          syllabusAnchor: "NEET PG — Community Medicine: epidemiology, biostatistics and screening.",
          mustCover: [
            "Descriptive, analytical and experimental designs, and the question each is built to answer",
            "Cohort studies: their direction in time, the measurement of incidence, relative risk, and the strengths and weaknesses that follow from the design",
            "Case-control studies: the odds ratio, the conditions under which it approximates relative risk, and why rare diseases suit this design",
            "Randomised controlled trials: randomisation, blinding, and the intention-to-treat principle",
            "Selection bias and information bias, each with a recognisable example",
            "Confounding, how it differs from bias, and the ways it is handled at the design stage and at the analysis stage",
            "Incidence and prevalence, the relationship between them through duration of disease, and why standardisation is needed to compare populations",
            "Screening test characteristics: sensitivity, specificity, positive and negative predictive value, and how prevalence moves the predictive values while leaving sensitivity and specificity unchanged",
            "The criteria that make a disease and a test suitable for screening, and how India's national health programmes are structured under the National Health Mission to deliver them",
          ],
          worked: ["Build a two-by-two table from an illustrative screening scenario, compute sensitivity, specificity and predictive values, then repeat it at a lower prevalence"],
          traps: [
            "Calculating relative risk from a case-control study, which can only yield an odds ratio",
            "Assuming a highly sensitive test must have a high positive predictive value in a low-prevalence population",
            "Treating confounding as a measurement problem that better data collection alone can fix",
          ],
          officialSources: [MOHFW, NHM],
          diagram: "compare",
          keywords: ["cohort vs case control study", "relative risk vs odds ratio", "sensitivity specificity predictive value", "bias and confounding epidemiology"],
          order: 0,
        },
      ],
    },
    {
      slug: "exam-craft",
      title: "Exam Craft",
      articles: [
        {
          slug: "neet-pg-revision-and-test-analysis",
          title: "NEET PG Revision: Weightage, Active Recall and Test Analysis",
          syllabusAnchor: "NEET PG — Examination scheme, subject weightage and preparation strategy.",
          mustCover: [
            "Approximate subject weightage, where marks concentrate, and how that should change the order in which subjects are revised",
            "Why active recall outperforms rereading, and how to convert a chapter into recall prompts rather than highlighted text",
            "Spaced repetition applied to a medical syllabus: what deserves scheduling, and how to keep the daily review load sustainable",
            "Image-based questions: building a deliberate image bank across pathology, radiology, dermatology and instruments",
            "Clinical vignette technique: reading the stem for the discriminating clue before looking at the options",
            "Grand test discipline: full-length timed papers under exam conditions rather than untimed subject-wise tests",
            "The error log method — classifying every mistake as a knowledge gap, a misread stem, a calculation slip or a guess, then reviewing by category",
            "Pacing across a long single-best-answer paper, flagging for review, and a last-30-day plan built on consolidation, daily tests and no new sources",
          ],
          worked: ["Turn one grand test result into a concrete revision plan by classifying every wrong answer in an error log and acting on the largest category"],
          traps: [
            "Adding new sources in the final month instead of consolidating material already revised",
            "Reviewing only the wrong answers and ignoring the questions answered correctly by guessing",
          ],
          officialSources: [NBE, NMC],
          diagram: "hierarchy",
          keywords: ["NEET PG preparation strategy", "NEET PG subject weightage", "spaced repetition medical exam", "grand test analysis error log"],
          order: 0,
        },
      ],
    },
  ],
};
