import type { StarterSubject } from "../types.js";

const NCERT = "https://ncert.nic.in/textbook.php";
const ARCHIVES = "https://www.nationalarchives.nic.in/";
const ASI = "https://asi.nic.in/";
const CENSUS = "https://censusindia.gov.in/";
const MOSPI = "https://mospi.gov.in/";

export const UPSC_HISTORY: StarterSubject = {
  slug: "upsc-history",
  name: "History & Indian Heritage",
  description: "Indian heritage, ancient to modern history and post-independence consolidation, mapped to GS Paper I.",
  paper: "GS Paper I",
  topics: [
    {
      slug: "ancient-and-medieval",
      title: "Ancient and Medieval India",
      articles: [
        {
          slug: "indus-valley-urban-planning",
          title: "Harappan Urban Planning: Cities, Drainage and Craft",
          syllabusAnchor: "GS Paper I — Indian culture will cover the salient aspects of Art Forms, Literature and Architecture from ancient to medieval times.",
          mustCover: [
            "The grid layout of Mohenjo-daro and Harappa, streets meeting at right angles, and the citadel and lower town division",
            "Standardised baked bricks in the 1:2:4 ratio across distant sites, and what that standardisation implies about administration",
            "The covered drainage system: house drains feeding street drains with manholes and soak pits",
            "The Great Bath and the granary structures at Mohenjo-daro, and the limits of the evidence for how they were used",
            "Site-level variation: Dholavira's three-part division and rock-cut reservoirs, Lothal's dock structure, Kalibangan's ploughed field",
            "Craft and trade evidence: seals, standardised weights in binary multiples, and contact with Mesopotamia recorded as Meluhha",
            "Competing explanations for de-urbanisation — river and climatic change, decline of long-distance trade, shifting settlement — rather than a single invasion",
          ],
          worked: ["Set Mohenjo-daro against Dholavira on layout, water management and building material, and say what each shows about local adaptation"],
          traps: [
            "Calling the Great Bath and the granary proven ritual or state structures — both labels are excavators' interpretations",
            "Explaining the decline by a single Aryan invasion, which the archaeological record does not support",
          ],
          officialSources: [NCERT, ASI],
          diagram: "hierarchy",
          keywords: [
            "indus valley urban planning",
            "harappan drainage system",
            "mohenjo daro town planning",
            "upsc ancient history notes",
          ],
          order: 0,
        },
        {
          slug: "mauryan-and-gupta-statecraft",
          title: "Mauryan and Gupta Statecraft Compared",
          syllabusAnchor: "Preliminary Examination — History of India and Indian National Movement.",
          mustCover: [
            "Mauryan central administration: the king in council, the mantriparishad, and the adhyakshas and tirthas described in the Arthashastra",
            "The provincial structure named in Ashokan edicts — Taxila, Ujjain, Tosali and Suvarnagiri — and the officials who inspected the provinces",
            "Ashokan dhamma: what the rock and pillar edicts actually prescribe, the dhamma-mahamattas, and dhamma as state policy rather than a religion",
            "Sources and their limits: the Arthashastra as a normative treatise, Megasthenes' Indica as later fragments, the edicts as direct evidence",
            "Gupta administration: land grants such as agrahara, the growth of intermediaries and feudatories, and weaker central control than the Mauryas",
            "Inscriptional self-presentation: Samudragupta's Prayaga Prashasti composed by Harishena, and what it claims about conquest and submission",
            "Currency and revenue: Mauryan punch-marked coins beside Gupta gold issues, and the debate over describing Gupta polity as feudal",
          ],
          worked: ["Set the two states side by side on appointment of officials, land revenue arrangements and degree of central control"],
          traps: [
            "Reading the Arthashastra as a description of the actual Mauryan state rather than a manual of how a state should be run",
            "Calling the Gupta period a uniform golden age without noting the evidence for deepening hierarchy and dependent labour",
          ],
          officialSources: [NCERT, ASI],
          diagram: "compare",
          keywords: [
            "mauryan administration upsc",
            "gupta empire polity",
            "ashokan edicts dhamma",
            "arthashastra state structure",
          ],
          order: 1,
        },
      ],
    },
    {
      slug: "modern-india",
      title: "Modern India and the Freedom Struggle",
      articles: [
        {
          slug: "from-1857-to-the-swadeshi-movement",
          title: "From 1857 to Swadeshi: The Making of Nationalism",
          syllabusAnchor: "GS Paper I — The Freedom Struggle: its various stages and important contributors/contributions from different parts of the country.",
          mustCover: [
            "Causes of the 1857 revolt across economic, administrative, military and religious grounds, and the immediate trigger in the army",
            "The geography of the revolt: its main centres and leaders, and the regions and social groups that stayed out or supported the Company",
            "The Government of India Act 1858 and the Queen's Proclamation: Company rule replaced by Crown rule, and the promises made to princes and landholders",
            "Why the revolt failed: no common programme, a limited social base, and superior British resources, communications and reinforcement",
            "The founding of the Indian National Congress in 1885, the moderate method of petition and constitutional agitation, and Dadabhai Naoroji's drain of wealth argument",
            "The partition of Bengal in 1905 and the Swadeshi and Boycott movement: its methods, its reach beyond Bengal, and its social limits",
            "The Surat split of 1907, and the difference between moderates and extremists on method and pace rather than on the goal",
            "The Indian Councils Act 1909 with its separate electorates, and the 1916 Home Rule Leagues and Lucknow Pact as the route back to unity",
          ],
          worked: ["Trace one demand — Indian representation in the legislative councils — from the moderates through 1909 to the Lucknow Pact, marking what changed at each step"],
          traps: [
            "Settling the label 'first war of independence' or 'mere mutiny' by assertion instead of by the evidence on both sides",
            "Treating the Swadeshi movement as purely economic when boycott, national education and passive resistance were equally central",
          ],
          officialSources: [NCERT, ARCHIVES],
          diagram: "timeline",
          keywords: [
            "revolt of 1857 causes",
            "swadeshi movement 1905",
            "moderates and extremists congress",
            "morley minto reforms 1909",
          ],
          order: 0,
        },
        {
          slug: "gandhian-mass-movements-and-colonial-reform",
          title: "Gandhian Mass Movements and Colonial Reform",
          syllabusAnchor: "GS Paper I — Modern Indian history from about the middle of the eighteenth century until the present: significant events, personalities, issues.",
          mustCover: [
            "The Rowlatt Act of 1919, the Jallianwala Bagh massacre, and the shift they produced in Congress method and membership",
            "The Government of India Act 1919: dyarchy in the provinces, the split between transferred and reserved subjects, and why it satisfied neither side",
            "The Khilafat alliance and the Non-Cooperation Movement of 1920-22: its constructive programme, its boycotts, and the withdrawal after Chauri Chaura",
            "The Simon Commission of 1927 and the Nehru Report of 1928 as the Indian counter-draft on constitutional advance",
            "Civil Disobedience from 1930: the Dandi march and salt as a chosen symbol, the Round Table Conferences, and the Gandhi-Irwin Pact of 1931",
            "The Communal Award of 1932 and the Poona Pact: separate electorates for the Depressed Classes replaced by reserved seats in joint electorates",
            "The Government of India Act 1935: provincial autonomy, the federal scheme that never came into force, and the 1937 provincial elections",
            "Quit India in 1942: the failure of the Cripps Mission, the 'do or die' call, and the largely leaderless character the movement took after the arrests",
          ],
          worked: ["Compare Non-Cooperation, Civil Disobedience and Quit India across programme, social base, government response and outcome"],
          traps: [
            "Saying the 1935 Act's federation was implemented — only the provincial part came into force",
            "Treating dyarchy as self-government when law and order, finance and revenue stayed reserved with the Governor",
          ],
          officialSources: [NCERT, ARCHIVES],
          diagram: "timeline",
          keywords: [
            "non cooperation movement 1920",
            "civil disobedience dandi march",
            "government of india act 1935",
            "quit india movement 1942",
          ],
          order: 1,
        },
      ],
    },
    {
      slug: "post-independence",
      title: "Post-Independence Consolidation",
      articles: [
        {
          slug: "princely-states-and-linguistic-reorganisation",
          title: "Princely States and the Redrawing of the Map",
          syllabusAnchor: "GS Paper I — Post-independence consolidation and reorganization within the country.",
          mustCover: [
            "The lapse of paramountcy in 1947 and the three options open to the princely states",
            "The Instrument of Accession and the standstill agreement as the working instruments of the States Department under Sardar Patel and V.P. Menon",
            "Why accession initially covered only defence, external affairs and communications, and how integration went further",
            "The three contested cases — Junagadh, Hyderabad and Jammu and Kashmir — and how each was settled",
            "Privy purses and princely privileges, and their abolition by the Twenty-sixth Amendment in 1971",
            "The Dhar Commission of 1948 and the JVP Committee of 1949: why linguistic reorganisation was first resisted",
            "Potti Sriramulu's fast and the creation of Andhra State in 1953 as the turning point, followed by the Fazl Ali States Reorganisation Commission and the States Reorganisation Act of 1956",
            "Later reorganisation on non-linguistic grounds, and the procedure Parliament follows under Article 3 to form a new state",
          ],
          worked: ["Take Hyderabad and Jammu and Kashmir and lay out the same sequence for each: standstill agreement, trigger, instrument used, final settlement"],
          traps: [
            "Assuming every state created after 1956 was carved out on a linguistic basis",
            "Treating accession and integration as one step when they were separate legal processes",
          ],
          officialSources: [NCERT, ARCHIVES],
          diagram: "timeline",
          keywords: [
            "integration of princely states",
            "states reorganisation act 1956",
            "instrument of accession",
            "linguistic reorganisation of states",
          ],
          order: 0,
        },
      ],
    },
    {
      slug: "art-and-culture",
      title: "Art, Architecture and Performing Traditions",
      articles: [
        {
          slug: "temple-architecture-and-classical-arts",
          title: "Temple Styles and the Classical Performing Arts",
          syllabusAnchor: "GS Paper I — Indian culture will cover the salient aspects of Art Forms, Literature and Architecture from ancient to medieval times.",
          mustCover: [
            "The shared vocabulary of the Hindu temple: garbhagriha, antarala, mandapa, the superstructure over the sanctum, and the temple plan they form",
            "Nagara: the curvilinear shikhara crowned by amalaka and kalasha, the absence of an elaborate boundary wall, and regional sub-styles including the Odisha deul and the Khajuraho group",
            "Dravida: the pyramidal vimana over the sanctum, the enclosing prakara, the towering gopuram over the gateway, and the temple tank",
            "Vesara as the Deccan blend of Nagara and Dravida features, seen in Chalukyan and Hoysala temples",
            "The rock-cut tradition from Ajanta and Ellora, including the monolithic Kailasa temple, and how it differs from structural temple building",
            "The eight classical dance forms recognised by the Sangeet Natak Akademi, the region of each, and the Natyashastra categories of nritta, nritya and abhinaya",
            "Hindustani and Carnatic music: raga and tala shared, and the gharana and composition traditions that separate them",
            "The Bhakti and Sufi movements — Alvars and Nayanars, Kabir, Nanak, Mirabai and Chaitanya, the Chishti and Suhrawardi silsilas — and their musical legacy in bhajan, kirtan and qawwali",
          ],
          worked: ["Set Nagara against Dravida across plan, superstructure, enclosure and gateway, with a named exemplar temple for each"],
          traps: [
            "Treating Vesara as an independent origin rather than a blend of the two older styles",
            "Listing dance forms without their region, or confusing Mohiniyattam with Kathakali when both come from Kerala",
          ],
          officialSources: [ASI, "https://www.indiaculture.gov.in/"],
          diagram: "hierarchy",
          keywords: [
            "nagara dravida vesara styles",
            "indian temple architecture upsc",
            "classical dance forms of india",
            "hindustani vs carnatic music",
          ],
          order: 0,
        },
      ],
    },
  ],
};

export const UPSC_GEOGRAPHY: StarterSubject = {
  slug: "upsc-geography",
  name: "Geography",
  description: "World physical geography, the Indian monsoon, and the resources and industry of India, mapped to GS Paper I.",
  paper: "GS Paper I",
  topics: [
    {
      slug: "physical-geography",
      title: "Physical Geography of the World",
      articles: [
        {
          slug: "earth-interior-and-plate-tectonics",
          title: "Interior of the Earth, Plate Tectonics and Landforms",
          syllabusAnchor: "GS Paper I — Salient features of world's physical geography.",
          mustCover: [
            "The layered interior — crust, mantle, outer core and inner core — and the Mohorovicic, Gutenberg and Lehmann discontinuities that separate them",
            "Seismic waves as the main evidence: how P and S waves behave in solids and liquids, and what the S wave shadow zone proves about the outer core",
            "Wegener's continental drift, the geological and fossil evidence he assembled, and the mechanism he could not supply",
            "Sea-floor spreading: mid-oceanic ridges, symmetrical palaeomagnetic stripes, and ocean floor that grows younger towards the ridge",
            "The three plate boundaries — divergent, convergent and transform — and the relative movement at each",
            "Landforms by boundary type: rift valleys and mid-oceanic ridges, deep sea trenches and island arcs, and fold mountains; the three convergence cases, with the Himalaya as continent-continent collision",
            "Why earthquakes and volcanoes concentrate along plate margins, and the intra-plate exception of hotspot volcanism",
          ],
          worked: ["Trace one convergent margin from subduction through trench, island arc and volcanic belt to its earthquake distribution, naming the plates involved"],
          traps: [
            "Treating continental drift and plate tectonics as the same theory rather than one superseding the other",
            "Assuming every volcano sits on a plate boundary when hotspot chains form well inside plates",
          ],
          officialSources: [NCERT],
          diagram: "flow",
          keywords: [
            "interior of the earth upsc",
            "plate tectonics landforms",
            "seismic shadow zone",
            "convergent boundary himalaya",
          ],
          order: 0,
        },
      ],
    },
    {
      slug: "climatology-india",
      title: "Climatology and the Indian Monsoon",
      articles: [
        {
          slug: "indian-monsoon-mechanism",
          title: "The Indian Monsoon: Mechanism, Breaks and Variability",
          syllabusAnchor: "GS Paper I — Salient features of world's physical geography.",
          mustCover: [
            "Global pressure belts and the tri-cellular circulation of Hadley, Ferrel and Polar cells, and the trade winds and westerlies they drive",
            "The seasonal migration of the Inter-Tropical Convergence Zone, and why the monsoon is now read as a shift of the ITCZ rather than only as a land-sea contrast",
            "Differential heating of land and sea, the classical thermal theory of the monsoon, and the observations it cannot explain",
            "Heating of the Tibetan plateau and the upper-air anticyclone it generates over the region",
            "The subtropical westerly jet withdrawing north of the Himalaya, and the tropical easterly jet establishing itself, as conditions for onset",
            "The Somali low-level jet and cross-equatorial flow that feed moisture into the south-west monsoon",
            "Onset and advance along the Arabian Sea and Bay of Bengal branches, break monsoon conditions, and withdrawal followed by north-east monsoon rainfall over the Tamil Nadu coast",
            "Ocean currents and sea surface temperature: warm and cold currents, upwelling off the Somali coast, and their effect on rainfall and fisheries",
            "El Nino, La Nina and the positive and negative phases of the Indian Ocean Dipole, and how each shifts Indian rainfall",
          ],
          worked: ["Work through one deficient monsoon year as a causal chain: sea surface temperature anomaly, circulation response, and the rainfall and cropping outcome"],
          traps: [
            "Explaining the monsoon only as a giant land-sea breeze, which accounts for neither its sudden onset nor its breaks",
            "Assuming every El Nino year must be a drought year when a favourable dipole phase can offset it",
          ],
          officialSources: ["https://mausam.imd.gov.in/", "https://www.tropmet.res.in/"],
          diagram: "flow",
          keywords: [
            "indian monsoon mechanism",
            "itcz and monsoon onset",
            "tropical easterly jet",
            "el nino iod indian rainfall",
          ],
          order: 0,
        },
      ],
    },
    {
      slug: "indian-geography",
      title: "Geography of India",
      articles: [
        {
          slug: "drainage-soils-and-cropping-patterns",
          title: "India's Drainage, Soils and Cropping Patterns",
          syllabusAnchor: "Preliminary Examination — Indian and World Geography: Physical, Social, Economic Geography of India and the World.",
          mustCover: [
            "Himalayan rivers: perennial and snow-fed, deep gorges and large deltas, and the Indus, Ganga and Brahmaputra systems with their main tributaries",
            "Peninsular rivers: seasonal flow, shallow valleys and fixed courses, and the east-flowing Mahanadi, Godavari, Krishna and Kaveri",
            "The west-flowing Narmada and Tapi occupying rift valleys, and why they form estuaries rather than deltas",
            "Drainage patterns — dendritic, trellis, radial and centripetal — with an Indian example of each, and the difference between a water divide and a drainage basin",
            "The eight soil types of the standard Indian classification and where each is distributed",
            "How parent rock, relief, rainfall and vegetation together produce alluvial, black and laterite soils in different regions",
            "Kharif, rabi and zaid seasons, and the temperature, rainfall and soil requirement that fixes each major crop's region",
            "Cropping patterns and cropping intensity, dryland against irrigated agriculture, and the regional concentration of rice, wheat, cotton and sugarcane",
          ],
          worked: ["Take one crop and explain its distribution from soil, rainfall, temperature and irrigation together rather than from soil alone"],
          traps: [
            "Calling every Himalayan river antecedent when only some cut across the range",
            "Memorising soils by state instead of deriving them from rock, relief and rainfall",
          ],
          officialSources: [NCERT, "https://agricoop.gov.in/"],
          diagram: "compare",
          keywords: [
            "himalayan vs peninsular rivers",
            "soil types of india",
            "kharif rabi zaid crops",
            "indian agriculture geography upsc",
          ],
          order: 0,
        },
      ],
    },
    {
      slug: "resources-and-industry",
      title: "Resources and Industrial Location",
      articles: [
        {
          slug: "minerals-energy-and-industrial-location",
          title: "Mineral Belts, Energy Resources and Industry",
          syllabusAnchor: "GS Paper I — Distribution of key natural resources across the world (including South Asia and the Indian sub-continent); factors responsible for the location of primary, secondary, and tertiary sector industries in various parts of the world (including India).",
          mustCover: [
            "Why minerals cluster: metallic minerals with ancient crystalline shields, and coal, petroleum and gas with sedimentary basins",
            "India's mineral belts: the north-eastern plateau belt of the Chhotanagpur region, the south-western belt of Karnataka and Goa, and the north-western belt of Rajasthan and Gujarat",
            "Coal: the Gondwana coalfields of the Damodar valley compared with the younger Tertiary coal of the north-east",
            "Petroleum and natural gas: onshore Assam, the offshore Mumbai High field, and the Krishna-Godavari basin",
            "Non-conventional energy: high solar potential in the arid north-west, wind along the western and southern coasts, and grid integration as the binding constraint",
            "Weber's least-cost theory, with transport cost, labour cost and agglomeration as the determinants of location, and the assumptions it rests on",
            "Weight-losing against weight-gaining industries, why iron and steel sits near coal and ore while sugar sits near cane, and how market and skilled labour dominate for footloose and knowledge industries",
          ],
          worked: ["Explain the location of one iron and steel plant using raw material, power, water, transport and market access together"],
          traps: [
            "Treating resource endowment as a sufficient explanation for industrial location without transport and market access",
            "Applying Weber's uniform plain and fixed transport cost assumptions without noting that they rarely hold",
          ],
          officialSources: [NCERT, MOSPI],
          diagram: "hierarchy",
          keywords: [
            "mineral belts of india",
            "industrial location factors",
            "weber least cost theory",
            "energy resources of india",
          ],
          order: 0,
        },
      ],
    },
  ],
};

export const UPSC_SOCIETY: StarterSubject = {
  slug: "upsc-society",
  name: "Indian Society & Social Justice",
  description: "Social structure, population and urbanisation, and the delivery of social justice across GS Papers I and II.",
  paper: "GS Paper I & II",
  topics: [
    {
      slug: "social-structure",
      title: "Structure of Indian Society",
      articles: [
        {
          slug: "diversity-caste-family-and-women",
          title: "Diversity, Caste, Family and the Position of Women",
          syllabusAnchor: "GS Paper I — Salient features of Indian Society, Diversity of India; role of women and women's organization.",
          mustCover: [
            "The dimensions of Indian diversity — linguistic, religious, regional and tribal — and the sources of unity that coexist with them",
            "Caste as a system: hierarchy, endogamy and hereditary occupation, and the difference between varna as a textual scheme and jati as a lived unit",
            "How caste has reorganised rather than disappeared: sanskritisation, the dominant caste in village society, and caste associations in electoral politics",
            "Family and household forms, joint and nuclear arrangements, and what urban employment and migration have changed",
            "Kinship and marriage rules, and the documented differences between northern and southern kinship patterns",
            "Patriarchy in practice: the division of unpaid work, property and inheritance, and the constraints behind low female labour force participation",
            "Women's organisations from the social reform era through the nationalist period to autonomous women's movements, and the shift from welfare to rights",
            "Tribal societies, their distinct social organisation, and the pressures of displacement, land alienation and assimilation",
          ],
          worked: ["Take one indicator such as female labour force participation and explain it through caste, class and region together rather than gender alone"],
          traps: [
            "Treating caste as a rural survival that modernisation will erase, when it has adapted to urban and political life",
            "Using 'women' as a single category and ignoring caste, class and regional differences within it",
          ],
          officialSources: [NCERT, CENSUS],
          diagram: "hierarchy",
          keywords: [
            "salient features of indian society",
            "caste system upsc notes",
            "role of women and women's organisations",
            "diversity of india gs1",
          ],
          order: 0,
        },
      ],
    },
    {
      slug: "population-and-urbanisation",
      title: "Population and Urbanisation",
      articles: [
        {
          slug: "population-composition-and-urban-growth",
          title: "Population Composition, Ageing and Urban Growth",
          syllabusAnchor: "GS Paper I — Population and associated issues, urbanization, their problems and their remedies.",
          mustCover: [
            "Census concepts that answer questions precisely: sex ratio, child sex ratio, literacy rate, population density, and the criteria that make a settlement a census town",
            "Age structure and the population pyramid, and the dependency ratio that follows from them",
            "The demographic transition model, and why Indian states sit at visibly different stages of it",
            "The demographic dividend: the window it opens, and the education, skilling and job creation needed to convert it into growth",
            "Ageing: the rising share of the elderly, its regional unevenness, and the pressure it puts on pensions, health and care",
            "Migration streams and their consequences for both source and destination regions, including peri-urban growth",
            "Urbanisation trends: concentration in large metropolitan centres, the growth of census towns, and the spread of unplanned peripheries",
            "Urban problems and remedies: housing and slums, water and sanitation, solid waste, congestion and air quality, set against the Seventy-fourth Amendment, municipal finance, master planning and public transport",
          ],
          worked: ["Read one state's age structure against another's and state what each implies for its schools, job creation and care services"],
          traps: [
            "Treating the demographic dividend as automatic rather than conditional on employment and human capital",
            "Confusing the sex ratio with the child sex ratio, which are computed for different populations",
          ],
          officialSources: [CENSUS, MOSPI],
          diagram: "flow",
          keywords: [
            "demographic dividend india",
            "census population composition",
            "urbanisation problems and remedies",
            "ageing population india",
          ],
          order: 0,
        },
      ],
    },
    {
      slug: "social-justice",
      title: "Social Justice and Development Outcomes",
      articles: [
        {
          slug: "welfare-schemes-health-and-education",
          title: "Welfare Schemes, Health and Education Outcomes",
          syllabusAnchor: "GS Paper II — Welfare schemes for vulnerable sections of the population by the Centre and States and the performance of these schemes.",
          mustCover: [
            "Who counts as a vulnerable section, and the constitutional basis for special provisions in their favour",
            "The main instruments of welfare — cash transfers, in-kind entitlements, employment guarantee and subsidised services — and what each is good at",
            "Rights-based entitlements compared with discretionary schemes, and why that difference changes accountability",
            "Targeting: exclusion and inclusion errors, beneficiary identification, and the trade-off with universal provision",
            "Delivery failures that recur: leakage, weak last-mile administrative capacity, and exclusion at the point of digital authentication",
            "How performance is actually assessed — outlay against outcome, independent evaluation, beneficiary feedback and social audit",
            "Health as a development indicator: out-of-pocket expenditure, low public health spending, and the balance between primary care and hospital care",
            "Education as a development indicator: the gap between enrolment and learning outcomes, and why states at similar income levels record very different results",
          ],
          worked: ["Take one welfare scheme and trace it from entitlement to outcome, naming the stage at which delivery usually breaks down"],
          traps: [
            "Judging a scheme by budget allocation or coverage numbers instead of by outcomes",
            "Assuming higher enrolment means higher learning, which the evidence treats as separate questions",
          ],
          officialSources: [MOSPI, CENSUS],
          diagram: "flow",
          keywords: [
            "welfare schemes vulnerable sections",
            "social justice gs2 notes",
            "health and education indicators india",
            "scheme implementation gaps",
          ],
          order: 0,
        },
      ],
    },
  ],
};
