import type { LegalSection } from "./types";
import { LEGAL_CONTACT_EMAIL } from "./types";

/** Interim Privacy sections (1–12). Pending counsel review. */
export const PRIVACY_SECTIONS_PART1: LegalSection[] = [
  {
    heading: "1. Who we are; scope; interim notice",
    paragraphs: [
      `Shelf (“myshelflib”, “we”, “us”) provides a personal study library and related tools. Privacy contact: ${LEGAL_CONTACT_EMAIL}.`,
      "This Privacy Policy (“Policy”) explains how we collect, use, store, share, and protect personal data when you use our websites, apps, APIs, and related services (the “Service”). It is a thorough interim notice intended to cover product reality and common Indian (DPDP Act 2023 / DPDP Rules), GDPR/UK GDPR, and CCPA/CPRA topics until a lawyer customizes it for your entity. It is not legal advice.",
      "It applies to personal data we process as a Data Fiduciary / controller for consumer accounts. If we process data solely on a school or company’s documented instructions under a separate DPA, that DPA may allocate roles differently.",
      "Related documents: Terms of Service (/legal/terms), Copyright (/legal/copyright).",
    ],
  },
  {
    heading: "2. Personal data we collect",
    paragraphs: [
      "We collect data you provide, data generated by your use, data from integrations you enable, and limited data from your device/browser.",
    ],
    bullets: [
      "Account & profile: name, email, password hash (email signup), Google ID / Telegram ID & username, avatar URL or uploaded image, role, study goal, plan/subscription flags, coin/affiliate balance, link codes for Telegram, timestamps.",
      "Authentication events: OTP send/verify for register and password reset; login method; session/JWT usage (token stored in your browser).",
      "Library & study materials: folders/collections, topics, pages; file bytes in object storage (PDF, imports, notebooks, Docs); titles/slugs; highlights, notes, pen strokes; stars; reading progress and last-read positions (synced and local); citations; share settings and tokens.",
      "Derived processing: HTML conversions, OCR text, embeddings/vector chunks for search and Study AI, processing status.",
      "Planner: tasks/events, notes, due dates, recurrence, completion state, optional links.",
      "Study AI: thread titles, messages, attachments, library/relevancy scope, tool-call traces needed to run tools, token/quota counters, model-mode selections.",
      "Quizzes: configuration, questions, answers (including uploaded working images), scores, timers, practice vs proctored flags, end reasons (e.g. tab/fullscreen/timer).",
      "Sharing: invitee emails, roles (viewer/editor), link-share tokens, “shared with me” relationships.",
      "Telegram: linkage status; files you forward to the bot; outbound share metadata when you send from Shelf.",
      "Payments: processor (e.g. Razorpay) identifiers, order/subscription status, plan period, coupons/affiliates—generally not full card PAN/CVV (handled by the processor).",
      "Communications: contact-form and support emails; transactional email logs (delivery metadata).",
      "Technical & security: IP address, user-agent, device/browser type, approximate location from IP, request logs, error/diagnostic traces, rate-limit signals, abuse signals.",
      "Analytics (if enabled): product-analytics identifiers and event properties (e.g. PostHog-compatible tools) such as feature usage, referrers, and coarse device info.",
      "Local device storage: localStorage (token, theme, reader workspace, greetings, Spotify recent URLs, etc.) and IndexedDB caches (e.g. PDF byte cache). Controlled by your browser; may remain after server deletion until you clear site data.",
    ],
  },
  {
    heading: "3. Sources of data",
    bullets: [
      "Directly from you (forms, uploads, chats, settings).",
      "Automatically from devices/browsers when you use the Service.",
      "From identity providers (Google, Telegram) when you choose those sign-in methods.",
      "From payment processors for billing status.",
      "From people who share library items with your email, if you accept/use them.",
      "From public Learn ingestion pipelines for catalog materials (not your private library).",
    ],
  },
  {
    heading: "4. Purposes of processing",
    bullets: [
      "Create and secure accounts; authenticate; recover passwords; prevent fraud and abuse.",
      "Provide library storage, reading, sync, search, indexing, OCR, and processing pipelines.",
      "Operate Study AI, quizzes, planner, sharing, and integrations you enable.",
      "Personalize UX (study goal, continue reading, greetings, suggestions).",
      "Bill Premium plans, apply coupons/affiliates, and send invoices/receipts via processors.",
      "Send transactional messages (OTP, security, service changes). Marketing only with consent or as otherwise permitted, with opt-out where required.",
      "Monitor reliability, debug, improve features, and produce aggregated/de-identified statistics.",
      "Comply with law, enforce Terms, handle takedown/legal requests, and protect rights and safety.",
    ],
  },
  {
    heading: "5. Legal bases (GDPR/UK and similar)",
    paragraphs: [
      "Where GDPR/UK GDPR or similar regimes apply, we rely on: (a) contract performance—to provide the Service you request; (b) legitimate interests—security, fraud prevention, product improvement, network integrity (balanced against your rights); (c) consent—where required (e.g. certain non-essential cookies, optional marketing, certain sensitive processing); (d) legal obligation—tax, accounting, lawful requests.",
      "Under India’s DPDP Act, we process personal data for specified purposes with consent or other lawful grounds recognized by that Act (such as employment is generally N/A here; legitimate uses specified in law). You may withdraw consent where processing is consent-based, without affecting prior lawful processing.",
    ],
  },
  {
    heading: "6. AI processing notice",
    paragraphs: [
      "When you use AI Features, prompts, selected text, retrieved library snippets, images, and related metadata are processed by us and by model/tool providers to generate responses and run tools (including optional web search/URL fetch). Do not submit data you are not allowed to share with such processors.",
      "Providers may process data in other countries. We configure vendors under their enterprise/API terms where available; training-on-your-data policies vary by vendor and plan—assume prompts may be logged by vendors for abuse monitoring unless a zero-retention contract is in place. Ask us if you need current vendor details for a diligence questionnaire.",
      "AI outputs can be inaccurate. See Terms for disclaimers.",
    ],
  },
  {
    heading: "7. Sharing; categories of recipients",
    paragraphs: [
      "We do not sell your personal information for money. We do not share it for cross-context behavioral advertising as a business model. We disclose data to:",
    ],
    bullets: [
      "Infrastructure: cloud hosting, Postgres, object storage (e.g. S3/R2/MinIO), CDNs, email delivery, vector databases.",
      "AI and tooling providers used for Study AI, OCR-adjacent pipelines, quiz vision grading, and similar.",
      "Auth/social: Google, Telegram when you use those features.",
      "Payments: Razorpay or successors for checkout and subscriptions.",
      "Analytics/error monitoring if enabled in the environment.",
      "Professional advisors (legal, accounting) under confidentiality.",
      "Authorities when required by law or to protect vital interests, security, or our legal rights.",
      "A buyer or successor in a merger, acquisition, financing, or sale of assets, subject to continuity of protections.",
      "Other users you explicitly share with (invitees or anyone who has your link token).",
    ],
  },
  {
    heading: "8. International transfers",
    paragraphs: [
      "Your data may be processed in India and in other countries where our processors operate (commonly including the US, EU, or other regions for AI/cloud). Where required, we use appropriate safeguards such as contractual clauses, vendor DPAs, and transfer assessments. Cross-border transfers remain subject to Indian DPDP rules and any government restrictions as they come into force.",
    ],
  },
  {
    heading: "9. Retention",
    paragraphs: [
      "We retain personal data only as long as needed for the purposes above. When you delete content in-product, associated vectors and derivatives are removed as jobs complete; residual copies may briefly remain in backups.",
    ],
    bullets: [
      "Account and library data: for the life of the account, then deletion/anonymization within a reasonable operational window after account deletion (often days to weeks for primary stores; backups longer).",
      "Security and server logs: typically shorter rolling windows unless needed for investigations.",
      "Payment/tax records: as required by financial law.",
      "Legal holds: longer if needed for disputes or lawful requests.",
      "Local device caches: until you clear them or uninstall/clear site data.",
    ],
  },
  {
    heading: "10. Security measures",
    paragraphs: [
      "We implement reasonable technical and organizational measures appropriate to risk, which may include TLS/HTTPS in transit, access controls, hashed passwords, least-privilege admin access, isolation of customer objects in storage keys, and monitoring. No method is perfectly secure. You must use strong unique passwords, protect your devices, and log out on shared computers.",
      "If we become aware of a personal data breach affecting you, we will take steps required by applicable law, which may include notifying the Data Protection Board of India / regulators and affected users without undue delay (commonly discussed as within about 72 hours for certain regimes where mandated), describing nature, likely impact, and measures taken—subject to law-enforcement delays.",
    ],
  },
  {
    heading: "11. Cookies, local storage, PWA, analytics",
    paragraphs: [
      "Essential storage: authentication tokens, CSRF-adjacent state if any, theme, reader workspace, feature flags needed for core UX. These are necessary for the Service.",
      "Functional: preferences such as study-goal UI state, recent Spotify URLs, offline queues.",
      "Analytics cookies/identifiers: used only if analytics is configured, to understand feature usage and improve the product.",
      "You can block cookies in browser settings; blocking essentials may break login. Clearing site data removes local PDF caches and offline drafts. Progressive Web App installs may keep caches until removed.",
      "We do not currently respond to browser “Do Not Track” signals in a special way beyond the controls in this Policy.",
    ],
  },
  {
    heading: "12. Children and teens",
    paragraphs: [
      "The Service is not directed to children under 13 (or a higher age required for digital consent where you live). We do not knowingly collect personal data from children below that age. Under Indian DPDP rules, processing children’s data may require verifiable parental consent and restrict tracking/ads—Shelf is not designed as a child-directed product.",
      "Users 13–17 should have guardian permission per our Terms. If you believe a child provided data without required consent, contact us and we will delete or restrict as required.",
    ],
  },
];
