import type { LucideIcon } from "lucide-react";
import {
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  CalendarDays,
  Columns2,
  FileSearch,
  FileText,
  FolderOpen,
  GraduationCap,
  Highlighter,
  Languages,
  LayoutDashboard,
  Library,
  ListChecks,
  Map,
  MessageSquareText,
  NotebookPen,
  PenLine,
  Scale,
  ScanSearch,
  Search,
  Share2,
  Sparkles,
  Stethoscope,
  Target,
  Users,
  Youtube,
} from "lucide-react";

/** Icons for /features intent cards — keyed by IntentCluster.id */
export const INTENT_CLUSTER_ICONS: Record<string, LucideIcon> = {
  "notes-pdfs-ask-llm": MessageSquareText,
  "personal-library": Library,
  "pdf-highlights": Highlighter,
  "reader-workspace": Columns2,
  "library-search": Search,
  "sketch-notes": NotebookPen,
  "research-doc-writing": BookMarked,
  "writing-assist-originality": ScanSearch,
  "continue-reading": BookOpen,
  streak: Target,
  "streak-share": Share2,
  "study-ai": Sparkles,
  "study-ai-page": MessageSquareText,
  "study-ai-library": Brain,
  "mind-maps": Map,
  "vs-chatbots": Sparkles,
  "exam-quiz": ListChecks,
  planner: CalendarDays,
  dashboard: LayoutDashboard,
  "share-shelf": Share2,
  "youtube-lectures": Youtube,
  telegram: Share2,
  spotify: BookOpen,
  offline: BookOpen,
  sync: BookOpen,
  privacy: FolderOpen,
  teachers: Users,
  college: GraduationCap,
  law: Scale,
  medical: Stethoscope,
  research: FileSearch,
  professionals: Briefcase,
  language: Languages,
  nonfiction: BookOpen,
  "goal-aware": Target,
  "all-in-one-study-workspace": LayoutDashboard,
  "student-study-tool": GraduationCap,
  "student-ask-llm": MessageSquareText,
  "teacher-prepare-tests": ListChecks,
  "teacher-study-materials": Users,
  "obsidian-alternative-study": NotebookPen,
  "notion-notebooklm-combo": LayoutDashboard,
  "exam-prep-study-tool": ListChecks,
  "homework-help-own-notes": PenLine,
  "vs-alternatives-pricing": Scale,
  "chat-with-pdf": FileText,
  "ai-pdf-summarizer": FileText,
  "ai-tutor": Sparkles,
  "ai-flashcards-quiz": ListChecks,
  "notebooklm-alternatives": Sparkles,
  "best-study-apps": GraduationCap,
  "free-ai-study": Sparkles,
  "remnote-quizlet-alts": ListChecks,
  "mind-map-pdf": Map,
  "youtube-lecture-notes-ai": Youtube,
  "goodnotes-web-alt": PenLine,
  "research-ai-papers": FileSearch,
  "study-planner-ai": CalendarDays,
  "paraphrase-notes-ai": ScanSearch,
};

export function iconForIntentCluster(id: string): LucideIcon {
  return INTENT_CLUSTER_ICONS[id] ?? BookOpen;
}
