ALTER TABLE "UserTopic" ADD COLUMN IF NOT EXISTS "completed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserTopic" ADD COLUMN IF NOT EXISTS "readPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserTopic" ADD COLUMN IF NOT EXISTS "starred" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserTopic" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
