import { Router, Request, Response } from "express";
import prisma from "../utils/prisma.js";
import { authMiddleware } from "../middleware/auth.js";
import { completeChat, streamChat } from "../services/llm.js";
import { logger, errorFields } from "../utils/logger.js";
import { answerWithRag } from "../services/rag.js";
import {
  PageAskPrepareError,
  preparePageAsk,
} from "../services/pageAskPrepare.js";
import {
  resolvePageAskThread,
  savePageAskTurn,
  titleFromQuery,
} from "../services/chatThreads.js";
import {
  QuotaError,
  assertLlmRoom,
  chatHistoryWindow,
  estimateTokens,
  shouldResetLlmWindow,
} from "../utils/quotas.js";

const router = Router();
router.use(authMiddleware);

type AskBody = {
  articleId?: string;
  userTopicId?: string;
  question?: string;
  selection?: string;
  mode?: string;
  imageBase64?: string;
  /** Save this exchange to Study AI history (reader panel). */
  persist?: boolean;
  /** Existing thread to append to; a page thread is reused/created otherwise. */
  threadId?: string;
  history?: Array<{
    role?: string;
    content?: string;
    imageBase64?: string;
  }>;
};

function writeSse(res: Response, event: string, data: unknown) {
  res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
}

/**
 * Reader Ask AI answers are generated by the page-ask pipeline but stored as a
 * normal chat thread, so the conversation survives reloads and can be continued
 * on /study-ai. Failing to save must never fail the answer.
 */
async function persistAskTurn(input: {
  userId: string;
  body: AskBody;
  question: string;
  answer: string;
}): Promise<string | null> {
  if (!input.body.persist || !input.answer.trim()) return null;
  try {
    const thread = await resolvePageAskThread({
      userId: input.userId,
      threadId: input.body.threadId,
      userTopicId: input.body.userTopicId,
      title: titleFromQuery(input.question),
    });
    if (!thread) return null;
    await savePageAskTurn({
      userId: input.userId,
      threadId: thread.id,
      threadTitle: thread.title,
      question: input.question,
      answer: input.answer,
      imageBase64: input.body.imageBase64,
    });
    return thread.id;
  } catch (err) {
    logger.error("study.ask.persist_failed", errorFields(err));
    return null;
  }
}

/** What the panel shows as the user's turn for the quick action buttons. */
function askTurnLabel(body: AskBody, mode: string): string {
  const question = String(body.question ?? "").trim();
  if (question) return question;
  if (mode === "summarize") return "Summarize this";
  if (mode === "notes") return "Make short notes";
  if (mode === "mindmap") return "Make a mind map";
  return "Explain the attached image.";
}

router.post("/ask", async (req: Request, res: Response) => {
  const body = req.body as AskBody;
  const userId = req.user!.userId;
  const askStarted = Date.now();
  logger.info("study.ask.start", {
    userId,
    userTopicId: body.userTopicId ?? null,
    articleId: body.articleId ?? null,
    mode: body.mode ?? "ask",
  });

  try {
    const prepared = await preparePageAsk({
      userId,
      ...body,
    });

    let tokensUsed = prepared.user.llmTokensUsed;
    if (shouldResetLlmWindow(prepared.user.llmTokensResetAt)) {
      await prisma.user.update({
        where: { id: userId },
        data: { llmTokensUsed: 0, llmTokensResetAt: new Date() },
      });
      tokensUsed = 0;
    }

    assertLlmRoom(
      { ...prepared.user, llmTokensUsed: tokensUsed },
      estimateTokens(prepared.estimatePrompt)
    );

    const { text: answer, tokens } = await completeChat(prepared.chatMessages);

    await prisma.user.update({
      where: { id: userId },
      data: { llmTokensUsed: { increment: tokens } },
    });

    const durationMs = Date.now() - askStarted;
    logger.info("study.ask.ok", {
      durationMs,
      usedVectors: prepared.needVectors,
      contextChars: prepared.packedChars,
      hasSelection: prepared.hasSelection,
      tokens,
    });

    const threadId = await persistAskTurn({
      userId,
      body,
      question: askTurnLabel(body, prepared.resolvedMode),
      answer,
    });

    res.json({
      answer,
      threadId,
      mode: prepared.resolvedMode,
      tokensUsed: tokens,
      memoryLimit: chatHistoryWindow(prepared.user) * 2,
      contextChars: prepared.packedChars,
      usedSelection: prepared.hasSelection,
      usedVectors: prepared.needVectors,
      durationMs,
    });
  } catch (err) {
    if (err instanceof PageAskPrepareError) {
      res.status(err.status).json({ error: err.message });
      return;
    }
    if (err instanceof QuotaError) {
      res.status(err.status).json({ error: err.message });
      return;
    }
    logger.error("study.ask.failed", {
      ...errorFields(err),
      userTopicId: body.userTopicId ?? null,
      articleId: body.articleId ?? null,
    });
    const message = err instanceof Error ? err.message : "Study AI failed";
    res.status(503).json({ error: message });
  }
});

/** Cursor-style SSE: status stages + token deltas. */
router.post("/ask/stream", async (req: Request, res: Response) => {
  const body = req.body as AskBody;
  const userId = req.user!.userId;
  const askStarted = Date.now();
  logger.info("study.ask.stream.start", {
    userId,
    userTopicId: body.userTopicId ?? null,
    articleId: body.articleId ?? null,
    mode: body.mode ?? "ask",
  });

  res.setHeader("Content-Type", "text/event-stream; charset=utf-8");
  res.setHeader("Cache-Control", "no-cache, no-transform");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no");
  if (typeof (res as Response & { flushHeaders?: () => void }).flushHeaders === "function") {
    (res as Response & { flushHeaders: () => void }).flushHeaders();
  }

  const send = (event: string, data: unknown) => {
    if (res.writableEnded) return;
    writeSse(res, event, data);
  };

  try {
    send("status", { stage: "starting", detail: "Starting Study AI…" });

    const prepared = await preparePageAsk(
      { userId, ...body },
      (stage, detail) => send("status", { stage, detail })
    );

    let tokensUsed = prepared.user.llmTokensUsed;
    if (shouldResetLlmWindow(prepared.user.llmTokensResetAt)) {
      await prisma.user.update({
        where: { id: userId },
        data: { llmTokensUsed: 0, llmTokensResetAt: new Date() },
      });
      tokensUsed = 0;
    }

    assertLlmRoom(
      { ...prepared.user, llmTokensUsed: tokensUsed },
      estimateTokens(prepared.estimatePrompt)
    );

    send("status", { stage: "generating", detail: "Writing answer…" });

    let tokens = 0;
    let answer = "";
    for await (const ev of streamChat(prepared.chatMessages)) {
      if (ev.type === "delta") {
        answer += ev.text;
        send("delta", { text: ev.text });
      } else if (ev.type === "done") {
        tokens = ev.tokens;
        send("status", {
          stage: "finishing",
          detail: `Done · ${ev.model}`,
        });
      }
    }

    await prisma.user.update({
      where: { id: userId },
      data: { llmTokensUsed: { increment: tokens } },
    });

    const durationMs = Date.now() - askStarted;
    logger.info("study.ask.stream.ok", {
      durationMs,
      usedVectors: prepared.needVectors,
      contextChars: prepared.packedChars,
      tokens,
    });

    const threadId = await persistAskTurn({
      userId,
      body,
      question: askTurnLabel(body, prepared.resolvedMode),
      answer,
    });

    send("done", {
      threadId,
      mode: prepared.resolvedMode,
      tokensUsed: tokens,
      contextChars: prepared.packedChars,
      usedSelection: prepared.hasSelection,
      usedVectors: prepared.needVectors,
      durationMs,
      memoryLimit: chatHistoryWindow(prepared.user) * 2,
    });
    res.end();
  } catch (err) {
    const status =
      err instanceof QuotaError || err instanceof PageAskPrepareError
        ? err.status
        : 503;
    if (!(err instanceof QuotaError || err instanceof PageAskPrepareError)) {
      logger.error("study.ask.stream.failed", {
        ...errorFields(err),
        userTopicId: body.userTopicId ?? null,
        articleId: body.articleId ?? null,
      });
    }
    send("error", {
      message: err instanceof Error ? err.message : "Study AI failed",
      status,
    });
    res.end();
  }
});

router.post("/library-ask", async (req: Request, res: Response) => {
  const query = String((req.body as { query?: string }).query ?? "").trim();
  if (!query) {
    res.status(400).json({ error: "query required" });
    return;
  }

  const userId = req.user!.userId;
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: {
      studyGoal: true,
      plan: true,
      role: true,
      subscriptionExpiresAt: true,
      llmTokensUsed: true,
      llmTokensResetAt: true,
    },
  });
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }

  try {
    let tokensUsed = user.llmTokensUsed;
    if (shouldResetLlmWindow(user.llmTokensResetAt)) {
      await prisma.user.update({
        where: { id: userId },
        data: { llmTokensUsed: 0, llmTokensResetAt: new Date() },
      });
      tokensUsed = 0;
    }
    assertLlmRoom(
      { ...user, llmTokensUsed: tokensUsed },
      estimateTokens(query) + 800
    );

    const result = await answerWithRag({
      userId,
      query,
      studyGoal: user.studyGoal ?? "GENERAL",
    });

    await prisma.user.update({
      where: { id: userId },
      data: { llmTokensUsed: { increment: result.tokens } },
    });

    res.json({
      answer: result.answer,
      matchCount: result.matchCount,
      citations: result.citations,
    });
  } catch (err) {
    if (err instanceof QuotaError) {
      res.status(err.status).json({ error: err.message });
      return;
    }
    const message = err instanceof Error ? err.message : "Library search failed";
    res.status(503).json({ error: message });
  }
});

export default router;
