import { Router, Request, Response } from "express";
import prisma from "../utils/prisma.js";
import { authMiddleware } from "../middleware/auth.js";
import { logger, errorFields } from "../utils/logger.js";
import { answerWithRag } from "../services/rag.js";
import {
  PageAskPrepareError,
  preparePageAsk,
} from "../services/pageAskPrepare.js";
import {
  resolvePageAskThread,
  savePageAskTurn,
  titleFromQuery,
} from "../services/chatThreads.js";
import {
  completeWithStudyTools,
} from "../services/studyToolLoop.js";
import { streamMapReduceAnswer } from "../services/mapReduceSummary.js";
import { runStudyAskStream } from "./studyAskStreamRun.js";
import { studyToolLoopOpts } from "../services/studyToolOpts.js";
import {
  QuotaError,
  chatHistoryWindow,
} from "../utils/quotas.js";
import { assertLlmBudget, chargeLlmTokens } from "../utils/llmUsage.js";
import { recordProductFlow } from "../utils/appMetrics.js";
import {
  studyAiFailureStub,
  toUserFacingStudyError,
} from "../utils/studyAiUserError.js";
import {
  abortStudyStreamOnClientDisconnect,
  logStudyAiEmptyReply,
  logStudyAiStreamFailure,
} from "../utils/studyAiDiagnostics.js";

const router = Router();
router.use(authMiddleware);

type AskBody = {
  articleId?: string;
  userTopicId?: string;
  /** Shown in the chat bubble / history. */
  question?: string;
  /** Optional expanded prompt for the model (slash commands). */
  prompt?: string;
  selection?: string;
  mode?: string;
  depth?: string;
  imageBase64?: string;
  /** Allow web_search / fetch_url while reading a PDF (default off). */
  webSearch?: boolean;
  /** Save this exchange to Study AI history (reader panel). */
  persist?: boolean;
  /** Existing thread to append to; a page thread is reused/created otherwise. */
  threadId?: string;
  history?: Array<{
    role?: string;
    content?: string;
    imageBase64?: string;
  }>;
};

function writeSse(res: Response, event: string, data: unknown) {
  res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
}

/**
 * Reader Ask AI answers are generated by the page-ask pipeline but stored as a
 * normal chat thread, so the conversation survives reloads and can be continued
 * on /study-ai. Failing to save must never fail the answer.
 */
async function persistAskTurn(input: {
  userId: string;
  body: AskBody;
  question: string;
  answer: string;
}): Promise<string | null> {
  if (!input.body.persist || !input.answer.trim()) return null;
  try {
    const thread = await resolvePageAskThread({
      userId: input.userId,
      threadId: input.body.threadId,
      userTopicId: input.body.userTopicId,
      title: titleFromQuery(input.question),
    });
    if (!thread) return null;
    await savePageAskTurn({
      userId: input.userId,
      threadId: thread.id,
      threadTitle: thread.title,
      question: input.question,
      answer: input.answer,
      imageBase64: input.body.imageBase64,
    });
    return thread.id;
  } catch (err) {
    logger.error("study.ask.persist_failed", errorFields(err));
    return null;
  }
}

/** What the panel shows as the user's turn for the quick action buttons. */
function askTurnLabel(body: AskBody, mode: string): string {
  const question = String(body.question ?? "").trim();
  if (question) return question;
  if (mode === "summarize") return "Summarize this";
  if (mode === "deep-summary") return "Deep summary";
  if (mode === "analyze") return "Analyze this";
  if (mode === "notes") return "Make short notes";
  if (mode === "mindmap") return "Make a mind map";
  return "Explain the attached image.";
}

router.post("/ask", async (req: Request, res: Response) => {
  const body = req.body as AskBody;
  const userId = req.user!.userId;
  const askStarted = Date.now();
  logger.info("study.ask.start", {
    userId,
    userTopicId: body.userTopicId ?? null,
    articleId: body.articleId ?? null,
    mode: body.mode ?? "ask",
  });

  try {
    const prepared = await preparePageAsk({
      userId,
      articleId: body.articleId,
      userTopicId: body.userTopicId,
      question: body.question,
      prompt: body.prompt,
      selection: body.selection,
      mode: body.mode,
      depth: body.depth,
      imageBase64: body.imageBase64,
      history: body.history,
      webSearch: body.webSearch,
    });

    await assertLlmBudget(userId, 1);

    let answer = "";
    let tokens = 0;

    if (prepared.useMapReduce && prepared.mapReduceSections.length > 0) {
      try {
        for await (const ev of streamMapReduceAnswer({
          depth: prepared.depth,
          title: prepared.title,
          mode: prepared.resolvedMode,
          sections: prepared.mapReduceSections,
          systemPrompt: prepared.systemPrompt,
          mergeInstruction: prepared.mergeInstruction,
        })) {
          if (ev.type === "delta") answer += ev.text;
          else if (ev.type === "done") tokens = ev.tokens;
        }
      } catch (mapErr) {
        logger.warn("study.map_reduce.fallback", errorFields(mapErr));
        const result = await completeWithStudyTools(
          prepared.chatMessages,
          {
            userId,
            defaultPageId: prepared.defaultPageId,
            webSearch: prepared.webSearchEnabled,
            studyGoal: prepared.user.studyGoal,
          },
          { ...studyToolLoopOpts(prepared), metricsFlow: "study_ask" }
        );
        answer = result.text;
        tokens = result.tokens;
      }
    } else {
      const result = await completeWithStudyTools(
        prepared.chatMessages,
        {
          userId,
          defaultPageId: prepared.defaultPageId,
          webSearch: prepared.webSearchEnabled,
          studyGoal: prepared.user.studyGoal,
        },
        { ...studyToolLoopOpts(prepared), metricsFlow: "study_ask" }
      );
      answer = result.text;
      tokens = result.tokens;
    }

    await chargeLlmTokens(userId, tokens, "study_ask");

    const durationMs = Date.now() - askStarted;
    recordProductFlow({
      domain: "study",
      action: "ask",
      ok: true,
      durationMs,
    });
    logger.info("study.ask.ok", {
      durationMs,
      usedVectors: prepared.needVectors,
      contextChars: prepared.packedChars,
      hasSelection: prepared.hasSelection,
      tokens,
    });

    const threadId = await persistAskTurn({
      userId,
      body,
      question: askTurnLabel(body, prepared.resolvedMode),
      answer,
    });

    res.json({
      answer,
      threadId,
      mode: prepared.resolvedMode,
      tokensUsed: tokens,
      memoryLimit: chatHistoryWindow(prepared.user) * 2,
      contextChars: prepared.packedChars,
      usedSelection: prepared.hasSelection,
      usedVectors: prepared.needVectors,
      durationMs,
    });
  } catch (err) {
    if (err instanceof PageAskPrepareError) {
      res.status(err.status).json({ error: err.message });
      return;
    }
    if (err instanceof QuotaError) {
      res.status(err.status).json({ error: err.message });
      return;
    }
    logger.error("study.ask.failed", {
      ...errorFields(err),
      userTopicId: body.userTopicId ?? null,
      articleId: body.articleId ?? null,
    });
    const message = toUserFacingStudyError(err);
    res.status(503).json({ error: message });
  }
});

/** Cursor-style SSE: status stages + token deltas. */
router.post("/ask/stream", async (req: Request, res: Response) => {
  const body = req.body as AskBody;
  const userId = req.user!.userId;
  const askStarted = Date.now();
  logger.info("study.ask.stream.start", {
    userId,
    userTopicId: body.userTopicId ?? null,
    articleId: body.articleId ?? null,
    mode: body.mode ?? "ask",
  });

  res.setHeader("Content-Type", "text/event-stream; charset=utf-8");
  res.setHeader("Cache-Control", "no-cache, no-transform");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("X-Accel-Buffering", "no");
  if (typeof (res as Response & { flushHeaders?: () => void }).flushHeaders === "function") {
    (res as Response & { flushHeaders: () => void }).flushHeaders();
  }

  const send = (event: string, data: unknown) => {
    if (res.writableEnded) return;
    writeSse(res, event, data);
  };

  const llmAbort = new AbortController();
  abortStudyStreamOnClientDisconnect(res, llmAbort);

  try {
    send("status", { stage: "starting", detail: "Getting ready" });

    const prepared = await preparePageAsk(
      {
        userId,
        articleId: body.articleId,
        userTopicId: body.userTopicId,
        question: body.question,
        prompt: body.prompt,
        selection: body.selection,
        mode: body.mode,
        depth: body.depth,
        imageBase64: body.imageBase64,
        history: body.history,
        webSearch: body.webSearch,
      },
      (stage, detail) => send("status", { stage, detail })
    );

    await assertLlmBudget(userId, 1);

    send("status", { stage: "generating", detail: "Composing answer" });

    let tokens = 0;
    let answer = "";

    const streamResult = await runStudyAskStream(
      {
        prepared,
        userId,
        signal: llmAbort.signal,
      },
      (ev) => {
        if (ev.type === "status") {
          send("status", { stage: ev.stage, detail: ev.detail });
        } else if (ev.type === "delta") {
          send("delta", { text: ev.text });
        }
      }
    );
    tokens = streamResult.tokens;
    answer = streamResult.answer;

    await chargeLlmTokens(userId, tokens, "study_ask_stream");

    const durationMs = Date.now() - askStarted;
    recordProductFlow({
      domain: "study",
      action: "ask_stream",
      ok: true,
      durationMs,
    });
    logger.info("study.ask.stream.ok", {
      durationMs,
      usedVectors: prepared.needVectors,
      contextChars: prepared.packedChars,
      tokens,
    });

    if (!answer.trim()) {
      logStudyAiEmptyReply({
        channel: "page_ask_stream",
        reason: llmAbort.signal.aborted
          ? "client_aborted"
          : "no_text_after_stream",
        userId,
        mode: prepared.resolvedMode,
        depth: prepared.depth,
        tokens,
        toolsEnabled: prepared.toolsEnabled,
        aborted: llmAbort.signal.aborted,
        usedVectors: prepared.needVectors,
        contextChars: prepared.packedChars,
        mapReduce: prepared.useMapReduce,
      });
      const threadId = await persistAskTurn({
        userId,
        body,
        question: askTurnLabel(body, prepared.resolvedMode),
        answer: "Study AI could not finish this reply.",
      });
      send("error", {
        message: "Study AI couldn’t finish that reply. Please try again.",
        status: 503,
        threadId,
      });
      res.end();
      return;
    }

    const threadId = await persistAskTurn({
      userId,
      body,
      question: askTurnLabel(body, prepared.resolvedMode),
      answer,
    });

    send("done", {
      threadId,
      mode: prepared.resolvedMode,
      tokensUsed: tokens,
      contextChars: prepared.packedChars,
      usedSelection: prepared.hasSelection,
      usedVectors: prepared.needVectors,
      durationMs,
      memoryLimit: chatHistoryWindow(prepared.user) * 2,
    });
    res.end();
  } catch (err) {
    const status =
      err instanceof QuotaError || err instanceof PageAskPrepareError
        ? err.status
        : 503;
    if (!(err instanceof QuotaError || err instanceof PageAskPrepareError)) {
      logStudyAiStreamFailure("page_ask_stream", err, {
        userId,
        userTopicId: body.userTopicId ?? null,
        articleId: body.articleId ?? null,
        mode: body.mode ?? "ask",
        depth: body.depth ?? "quick",
      });
    }
    const message =
      err instanceof QuotaError || err instanceof PageAskPrepareError
        ? err.message
        : toUserFacingStudyError(err);
    const threadId = await persistAskTurn({
      userId,
      body,
      question: askTurnLabel(body, String(body.mode ?? "ask")),
      answer: studyAiFailureStub(
        err instanceof QuotaError || err instanceof PageAskPrepareError
          ? err
          : err
      ),
    });
    send("error", {
      message,
      status,
      threadId,
    });
    res.end();
  }
});

router.post("/library-ask", async (req: Request, res: Response) => {
  const query = String((req.body as { query?: string }).query ?? "").trim();
  if (!query) {
    res.status(400).json({ error: "query required" });
    return;
  }

  const userId = req.user!.userId;
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: {
      studyGoal: true,
      plan: true,
      role: true,
      subscriptionExpiresAt: true,
      llmTokensUsed: true,
      llmTokensResetAt: true,
    },
  });
  if (!user) {
    res.status(404).json({ error: "User not found" });
    return;
  }

  try {
    await assertLlmBudget(userId, 1);

    const result = await answerWithRag({
      userId,
      query,
      studyGoal: user.studyGoal ?? "GENERAL",
      metricsFlow: "study_library_ask",
    });

    await chargeLlmTokens(userId, result.tokens, "study_library_ask");
    recordProductFlow({
      domain: "study",
      action: "library_ask",
      ok: true,
    });

    res.json({
      answer: result.answer,
      matchCount: result.matchCount,
      citations: result.citations,
    });
  } catch (err) {
    if (err instanceof QuotaError) {
      res.status(err.status).json({ error: err.message });
      return;
    }
    const message = err instanceof Error ? err.message : "Library search failed";
    res.status(503).json({ error: message });
  }
});

export default router;
