import type { PreloadedCatalogEntry } from "./types.js";

/** NCERT textbooks — official PDFs and portal (UPSC / State PCS foundations). */
export const PRELOADED_CATALOG_NCERT: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "portal",
    topicTitle: "Browse all",
    studyGoal: "UPSC",
    title: "NCERT textbook portal",
    slug: "ncert-textbook-portal",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary:
      "Official NCERT e-textbook library — pick class and subject to open any school textbook PDF.",
    order: 0,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "history",
    topicTitle: "History",
    studyGoal: "UPSC",
    title: "Class 11 — Themes in World History",
    slug: "ncert-history-11-world",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/hess2ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "World history foundations for UPSC and school-level revision.",
    order: 1,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "history",
    topicTitle: "History",
    studyGoal: "UPSC",
    title: "Class 12 — Themes in Indian History I",
    slug: "ncert-history-12-part-1",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/hess301.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Ancient and early medieval India — core NCERT for history optional and GS.",
    order: 2,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "history",
    topicTitle: "History",
    studyGoal: "UPSC",
    title: "Class 12 — Themes in Indian History II",
    slug: "ncert-history-12-part-2",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/hess302.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Medieval and early modern India.",
    order: 3,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "history",
    topicTitle: "History",
    studyGoal: "UPSC",
    title: "Class 12 — Themes in Indian History III",
    slug: "ncert-history-12-part-3",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/hess303.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Modern India — essential prelims and mains background.",
    order: 4,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "history",
    topicTitle: "History",
    studyGoal: "UPSC",
    title: "Class 6 — Our Past I",
    slug: "ncert-history-6",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/gess1ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Introductory ancient history — quick revision of timelines and themes.",
    order: 5,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "geography",
    topicTitle: "Geography",
    studyGoal: "UPSC",
    title: "Class 11 — Fundamentals of Physical Geography",
    slug: "ncert-geo-11-physical",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/gegp1ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Physical geography concepts — landforms, climate, and geomorphology basics.",
    order: 1,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "geography",
    topicTitle: "Geography",
    studyGoal: "UPSC",
    title: "Class 11 — India — Physical Environment",
    slug: "ncert-geo-11-india",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/gegp2ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Indian physical geography — relief, drainage, and regional patterns.",
    order: 2,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "geography",
    topicTitle: "Geography",
    studyGoal: "UPSC",
    title: "Class 12 — Fundamentals of Human Geography",
    slug: "ncert-geo-12-human",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary: "Human geography — population, settlements, and economic activity.",
    order: 3,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "geography",
    topicTitle: "Geography",
    studyGoal: "UPSC",
    title: "Class 12 — India — People and Economy",
    slug: "ncert-geo-12-india-economy",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary: "Indian human geography — resources, agriculture, and industry.",
    order: 4,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "polity",
    topicTitle: "Polity",
    studyGoal: "UPSC",
    title: "Class 11 — Indian Constitution at Work",
    slug: "ncert-polity-11-constitution",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/leps1ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Constitutional institutions and democratic politics — Laxmikanth companion.",
    order: 1,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "polity",
    topicTitle: "Polity",
    studyGoal: "UPSC",
    title: "Class 12 — Politics in India since Independence",
    slug: "ncert-polity-12-politics",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/leps2ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Post-independence political history and party system evolution.",
    order: 2,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "polity",
    topicTitle: "Polity",
    studyGoal: "UPSC",
    title: "Class 9 — Democratic Politics I",
    slug: "ncert-polity-9",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/jess4ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Basics of democracy and electoral politics — quick polity refresh.",
    order: 3,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "economy",
    topicTitle: "Economy",
    studyGoal: "UPSC",
    title: "Class 11 — Indian Economic Development",
    slug: "ncert-economy-11",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/keec1ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Indian economy fundamentals — growth, sectors, and development challenges.",
    order: 1,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "economy",
    topicTitle: "Economy",
    studyGoal: "UPSC",
    title: "Class 12 — Introductory Macroeconomics",
    slug: "ncert-economy-12-macro",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/leec1ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Macroeconomic concepts — national income, money, and fiscal policy basics.",
    order: 2,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "science-environment",
    topicTitle: "Science & environment",
    studyGoal: "UPSC",
    title: "Class 12 — Biology",
    slug: "ncert-biology-12",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/lebo1ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Senior secondary biology — ecology and human health themes for environment GS.",
    order: 1,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "science-environment",
    topicTitle: "Science & environment",
    studyGoal: "UPSC",
    title: "Class 12 — Chemistry Part I",
    slug: "ncert-chemistry-12-part-1",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/lech1ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Chemistry fundamentals — useful for science & tech prelims revision.",
    order: 2,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "society",
    topicTitle: "Society",
    studyGoal: "UPSC",
    title: "Class 12 — Indian Society",
    slug: "ncert-society-12",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary: "Social structure, change, and challenges — GS society paper foundations.",
    order: 1,
  },
  {
    subjectSlug: "ncert",
    subjectName: "NCERT",
    topicSlug: "society",
    topicTitle: "Society",
    studyGoal: "UPSC",
    title: "Class 11 — Understanding Society",
    slug: "ncert-society-11",
    sourceUrl: "https://ncert.nic.in/textbook/pdf/hess4ps.pdf",
    license: "OFFICIAL_DOCUMENT",
    summary: "Sociological concepts — socialisation, culture, and social institutions.",
    order: 2,
  },
];
