import type { PreloadedCatalogEntry } from "./types.js";

/** Public open-learning portals — GENERAL track, Open Textbooks browse area. */
export const PRELOADED_CATALOG_OPEN_TEXTBOOKS: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "india-open-learning",
    topicTitle: "India — open learning",
    studyGoal: "GENERAL",
    title: "NCERT textbooks",
    slug: "ncert-textbooks",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary:
      "Official NCERT e-textbooks across classes — free government school textbooks.",
    order: 1,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "india-open-learning",
    topicTitle: "India — open learning",
    studyGoal: "GENERAL",
    title: "NIOS — Open School",
    slug: "nios-open-school",
    sourceUrl: "https://www.nios.ac.in/",
    license: "LINK_ONLY",
    summary:
      "National Institute of Open Schooling — open secondary and senior-secondary courses.",
    order: 2,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "india-open-learning",
    topicTitle: "India — open learning",
    studyGoal: "GENERAL",
    title: "SWAYAM — MOOC portal",
    slug: "swayam-moocs",
    sourceUrl: "https://swayam.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Government of India MOOC platform — free courses from universities and IITs.",
    order: 3,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "india-open-learning",
    topicTitle: "India — open learning",
    studyGoal: "GENERAL",
    title: "National Digital Library of India",
    slug: "ndli-portal",
    sourceUrl: "https://ndl.iitkgp.ac.in/",
    license: "LINK_ONLY",
    summary:
      "NDLI — searchable repository of books, papers, and learning material from Indian institutions.",
    order: 4,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "india-open-learning",
    topicTitle: "India — open learning",
    studyGoal: "GENERAL",
    title: "NPTEL — IIT video courses",
    slug: "open-nptel",
    sourceUrl: "https://nptel.ac.in/",
    license: "LINK_ONLY",
    summary:
      "Government-funded engineering and science video courses with lecture notes.",
    order: 5,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "india-open-learning",
    topicTitle: "India — open learning",
    studyGoal: "GENERAL",
    title: "e-PG Pathshala",
    slug: "epg-pathshala",
    sourceUrl: "https://epgp.inflibnet.ac.in/Home",
    license: "LINK_ONLY",
    summary:
      "INFLIBNET e-PG Pathshala — open postgraduate e-content across 70+ disciplines (MoE NME-ICT).",
    order: 6,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "international-open",
    topicTitle: "International open access",
    studyGoal: "GENERAL",
    title: "OpenStax — free textbooks",
    slug: "openstax-textbooks",
    sourceUrl: "https://openstax.org/",
    license: "LINK_ONLY",
    summary:
      "Peer-reviewed open textbooks for college-level maths, science, and humanities.",
    order: 1,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "international-open",
    topicTitle: "International open access",
    studyGoal: "GENERAL",
    title: "MIT OpenCourseWare",
    slug: "mit-ocw",
    sourceUrl: "https://ocw.mit.edu/",
    license: "LINK_ONLY",
    summary:
      "MIT course materials — syllabi, notes, and assignments across disciplines.",
    order: 2,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "international-open",
    topicTitle: "International open access",
    studyGoal: "GENERAL",
    title: "Project Gutenberg",
    slug: "project-gutenberg",
    sourceUrl: "https://www.gutenberg.org/",
    license: "LINK_ONLY",
    summary:
      "Public-domain ebooks — classic literature and reference works free to read.",
    order: 3,
  },
  {
    subjectSlug: "open-textbooks",
    subjectName: "Open Textbooks",
    topicSlug: "international-open",
    topicTitle: "International open access",
    studyGoal: "GENERAL",
    title: "Directory of Open Access Books",
    slug: "doab-portal",
    sourceUrl: "https://www.doabooks.org/",
    license: "LINK_ONLY",
    summary:
      "DOAB index of peer-reviewed open-access academic books from university presses.",
    order: 4,
  },
];
