import type { PreloadedCatalogEntry } from "./types.js";

export const PRELOADED_CATALOG_GATE: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "gate-official",
    subjectName: "GATE Official",
    topicSlug: "exam-portal",
    topicTitle: "Exam portal",
    studyGoal: "GATE",
    title: "GATE 2026 — IIT Guwahati",
    slug: "gate-2026-iitg",
    sourceUrl: "https://gate2026.iitg.ac.in/",
    license: "LINK_ONLY",
    summary:
      "Official GATE conducting IIT website — brochure, syllabus, and exam notices.",
    order: 1,
  },
  {
    subjectSlug: "gate-official",
    subjectName: "GATE Official",
    topicSlug: "exam-portal",
    topicTitle: "Exam portal",
    studyGoal: "GATE",
    title: "NPTEL — IIT course portal",
    slug: "nptel-courses",
    sourceUrl: "https://nptel.ac.in/",
    license: "LINK_ONLY",
    summary:
      "Government-funded NPTEL video courses and notes for engineering GATE subjects.",
    order: 2,
  },
  {
    subjectSlug: "gate-official",
    subjectName: "GATE Official",
    topicSlug: "exam-portal",
    topicTitle: "Exam portal",
    studyGoal: "GATE",
    title: "NCERT science foundations",
    slug: "gate-ncert-science",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary: "NCERT science textbooks useful for GATE XL and general aptitude.",
    order: 3,
  },
];

export const PRELOADED_CATALOG_CA: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "ICAI — Institute of Chartered Accountants",
    slug: "icai-home",
    sourceUrl: "https://www.icai.org/",
    license: "LINK_ONLY",
    summary:
      "Official ICAI portal — announcements, exam schedules, and standards.",
    order: 1,
  },
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "Ministry of Corporate Affairs",
    slug: "mca-gov",
    sourceUrl: "https://www.mca.gov.in/",
    license: "LINK_ONLY",
    summary: "Companies Act, LLP rules, and corporate law notifications from MCA.",
    order: 2,
  },
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "Income Tax Department",
    slug: "income-tax-portal",
    sourceUrl: "https://www.incometax.gov.in/",
    license: "LINK_ONLY",
    summary: "Official income tax portal — rules, circulars, and taxpayer services.",
    order: 3,
  },
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "GST portal",
    slug: "gst-official",
    sourceUrl: "https://www.gst.gov.in/",
    license: "LINK_ONLY",
    summary: "Official GST portal — indirect tax updates and compliance resources.",
    order: 4,
  },
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "Union Budget — CA relevance",
    slug: "ca-budget-portal",
    sourceUrl: "https://www.indiabudget.gov.in/",
    license: "OFFICIAL_DOCUMENT",
    summary: "Official budget documents for taxation and fiscal policy questions.",
    order: 5,
  },
];

export const PRELOADED_CATALOG_NEET: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "regulatory",
    topicTitle: "Regulatory bodies",
    studyGoal: "NEET_PG",
    title: "National Medical Commission",
    slug: "nmc-official",
    sourceUrl: "https://www.nmc.org.in/",
    license: "LINK_ONLY",
    summary:
      "Official NMC portal — medical education standards and notifications.",
    order: 1,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "regulatory",
    topicTitle: "Regulatory bodies",
    studyGoal: "NEET_PG",
    title: "National Board of Examinations",
    slug: "nbe-official",
    sourceUrl: "https://natboard.edu.in/",
    license: "LINK_ONLY",
    summary:
      "Official NBE site — NEET-PG, FMGE, and postgraduate exam information.",
    order: 2,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "regulatory",
    topicTitle: "Regulatory bodies",
    studyGoal: "NEET_PG",
    title: "NCERT biology textbooks",
    slug: "neet-ncert-biology",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary: "Official NCERT biology textbooks — preclinical foundations for NEET-PG.",
    order: 3,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "regulatory",
    topicTitle: "Regulatory bodies",
    studyGoal: "NEET_PG",
    title: "Ministry of Health & Family Welfare",
    slug: "mohfw-official",
    sourceUrl: "https://www.mohfw.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Official MoHFW portal — national health programmes, policies, and notifications.",
    order: 4,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "regulatory",
    topicTitle: "Regulatory bodies",
    studyGoal: "NEET_PG",
    title: "Indian Council of Medical Research",
    slug: "icmr-official",
    sourceUrl: "https://main.icmr.nic.in/",
    license: "LINK_ONLY",
    summary:
      "ICMR — national health research guidelines, reports, and disease advisories.",
    order: 5,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "clinical-reference",
    topicTitle: "Clinical reference",
    studyGoal: "NEET_PG",
    title: "AIIMS New Delhi",
    slug: "aiims-delhi",
    sourceUrl: "https://www.aiims.edu/",
    license: "LINK_ONLY",
    summary:
      "All India Institute of Medical Sciences — clinical departments and academic resources.",
    order: 1,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "clinical-reference",
    topicTitle: "Clinical reference",
    studyGoal: "NEET_PG",
    title: "PGIMER Chandigarh",
    slug: "pgimer-chandigarh",
    sourceUrl: "https://pgimer.edu.in/",
    license: "LINK_ONLY",
    summary:
      "Postgraduate Institute of Medical Education and Research — academic and clinical portal.",
    order: 2,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "exams",
    topicTitle: "Entrance exams",
    studyGoal: "NEET_PG",
    title: "National Testing Agency",
    slug: "nta-neet-portal",
    sourceUrl: "https://www.nta.ac.in/",
    license: "LINK_ONLY",
    summary:
      "Official NTA portal — NEET-UG, NEET-PG, and other national medical entrance notices.",
    order: 1,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "exams",
    topicTitle: "Entrance exams",
    studyGoal: "NEET_PG",
    title: "FMGE information — NBE",
    slug: "fmge-nbe",
    sourceUrl: "https://natboard.edu.in/fmge",
    license: "LINK_ONLY",
    summary:
      "Foreign Medical Graduate Examination details from the National Board of Examinations.",
    order: 2,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "curriculum",
    topicTitle: "Curriculum",
    studyGoal: "NEET_PG",
    title: "NMC — Competency-based curriculum",
    slug: "nmc-cbme",
    sourceUrl: "https://www.nmc.org.in/information-desk/for-students/",
    license: "LINK_ONLY",
    summary:
      "NMC student information desk — CBME modules and medical education standards.",
    order: 1,
  },
];

export const PRELOADED_CATALOG_JUDICIARY: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "India Code — Bare Acts",
    slug: "judiciary-india-code",
    sourceUrl: "https://www.indiacode.nic.in/",
    license: "LINK_ONLY",
    summary:
      "Authoritative bare acts for judiciary and judicial services preparation.",
    order: 1,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "Supreme Court of India",
    slug: "supreme-court-india",
    sourceUrl: "https://main.sci.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Official Supreme Court portal — judgments, cause lists, and circulars.",
    order: 2,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "Law Commission of India",
    slug: "law-commission",
    sourceUrl: "https://lawcommissionofindia.nic.in/",
    license: "LINK_ONLY",
    summary:
      "Official Law Commission reports and consultation papers on legal reform.",
    order: 3,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "eGazette — statutory notifications",
    slug: "judiciary-egazette",
    sourceUrl: "https://egazette.gov.in/",
    license: "LINK_ONLY",
    summary: "Central gazette for new acts, rules, and amendments.",
    order: 4,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "Legislative Department — Acts of Parliament",
    slug: "legislative-department",
    sourceUrl: "https://legislative.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Official Legislative Department portal — Central Acts and constitutional documents.",
    order: 5,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "Department of Justice",
    slug: "doj-india",
    sourceUrl: "https://doj.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Ministry of Law and Justice — access to justice programmes and legal aid schemes.",
    order: 6,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "courts",
    topicTitle: "Courts & profession",
    studyGoal: "JUDICIARY",
    title: "eCourts Services",
    slug: "ecourts-india",
    sourceUrl: "https://ecourts.gov.in/",
    license: "LINK_ONLY",
    summary:
      "National eCourts portal — case status, cause lists, and court services across India.",
    order: 1,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "courts",
    topicTitle: "Courts & profession",
    studyGoal: "JUDICIARY",
    title: "Bar Council of India",
    slug: "bar-council-india",
    sourceUrl: "https://www.barcouncilofindia.org/",
    license: "LINK_ONLY",
    summary:
      "Regulator for legal education and the advocate profession in India.",
    order: 2,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "courts",
    topicTitle: "Courts & profession",
    studyGoal: "JUDICIARY",
    title: "National Judicial Academy",
    slug: "nja-india",
    sourceUrl: "https://www.nja.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Training academy for judges — publications and judicial education resources.",
    order: 3,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "courts",
    topicTitle: "Courts & profession",
    studyGoal: "JUDICIARY",
    title: "National Legal Services Authority",
    slug: "nalsa-india",
    sourceUrl: "https://nalsa.gov.in/",
    license: "LINK_ONLY",
    summary:
      "NALSA — legal services, Lok Adalat, and access-to-justice initiatives.",
    order: 4,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "reports",
    topicTitle: "Reports & research",
    studyGoal: "JUDICIARY",
    title: "PRS Legislative Research",
    slug: "prs-legislative",
    sourceUrl: "https://prsindia.org/",
    license: "LINK_ONLY",
    summary:
      "Independent legislative research — bill summaries and policy analysis for mains answers.",
    order: 1,
  },
];
