import type { PreloadedCatalogEntry } from "./types.js";

/** Official government & institutional sources — embed in Learn, save per license tier. */
export const PRELOADED_CATALOG_UPSC: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "official-portals",
    subjectName: "Official Portals",
    topicSlug: "government",
    topicTitle: "Government of India",
    studyGoal: "UPSC",
    title: "India Code — Bare Acts & regulations",
    slug: "india-code-bare-acts",
    sourceUrl: "https://www.indiacode.nic.in/",
    license: "LINK_ONLY",
    summary:
      "Official repository of Central Acts and subordinate legislation. Browse and cite bare acts from the Government of India.",
    order: 1,
  },
  {
    subjectSlug: "official-portals",
    subjectName: "Official Portals",
    topicSlug: "government",
    topicTitle: "Government of India",
    studyGoal: "UPSC",
    title: "eGazette of India",
    slug: "egazette-india",
    sourceUrl: "https://egazette.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Official gazette notifications from the Government of India — appointments, rules, and statutory orders.",
    order: 2,
  },
  {
    subjectSlug: "official-portals",
    subjectName: "Official Portals",
    topicSlug: "government",
    topicTitle: "Government of India",
    studyGoal: "UPSC",
    title: "Reserve Bank of India",
    slug: "rbi-official",
    sourceUrl: "https://www.rbi.org.in/",
    license: "LINK_ONLY",
    summary:
      "Official RBI site — monetary policy, reports, and banking regulations for economy and finance papers.",
    order: 3,
  },
  {
    subjectSlug: "official-portals",
    subjectName: "Official Portals",
    topicSlug: "government",
    topicTitle: "Government of India",
    studyGoal: "UPSC",
    title: "NITI Aayog",
    slug: "niti-aayog",
    sourceUrl: "https://www.niti.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Policy think tank of the Government of India — strategy documents, indices, and development reports.",
    order: 4,
  },
  {
    subjectSlug: "official-portals",
    subjectName: "Official Portals",
    topicSlug: "government",
    topicTitle: "Government of India",
    studyGoal: "UPSC",
    title: "Ministry of External Affairs",
    slug: "mea-official",
    sourceUrl: "https://www.mea.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Official MEA portal — bilateral relations, treaties, and press releases for international relations.",
    order: 5,
  },
  {
    subjectSlug: "official-portals",
    subjectName: "Official Portals",
    topicSlug: "government",
    topicTitle: "Government of India",
    studyGoal: "UPSC",
    title: "Census of India",
    slug: "census-india",
    sourceUrl: "https://censusindia.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Official census data and publications from the Registrar General of India.",
    order: 6,
  },
  {
    subjectSlug: "official-portals",
    subjectName: "Official Portals",
    topicSlug: "government",
    topicTitle: "Government of India",
    studyGoal: "UPSC",
    title: "UPSC — Examinations home",
    slug: "upsc-exams-home",
    sourceUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    license: "LINK_ONLY",
    summary:
      "Union Public Service Commission — active examinations, calendars, and official notices.",
    order: 7,
  },
  {
    subjectSlug: "indian-economy",
    subjectName: "Indian Economy",
    topicSlug: "budget-survey",
    topicTitle: "Budget & Survey",
    studyGoal: "UPSC",
    title: "Union Budget documents",
    slug: "union-budget-portal",
    sourceUrl: "https://www.indiabudget.gov.in/",
    license: "OFFICIAL_DOCUMENT",
    summary:
      "Official India Budget portal — budget speech, economic survey, and statistical appendices.",
    order: 1,
  },
];

export const PRELOADED_CATALOG_STATE: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "state-pcs-portals",
    subjectName: "State PCS Resources",
    topicSlug: "official-links",
    topicTitle: "Official links",
    studyGoal: "STATE_PCS",
    title: "India Code — State & Central Acts",
    slug: "state-india-code",
    sourceUrl: "https://www.indiacode.nic.in/",
    license: "LINK_ONLY",
    summary: "Bare acts and rules for State PCS law and polity preparation.",
    order: 1,
  },
  {
    subjectSlug: "state-pcs-portals",
    subjectName: "State PCS Resources",
    topicSlug: "official-links",
    topicTitle: "Official links",
    studyGoal: "STATE_PCS",
    title: "eGazette notifications",
    slug: "state-egazette",
    sourceUrl: "https://egazette.gov.in/",
    license: "LINK_ONLY",
    summary: "Central gazette updates relevant to State PCS current affairs.",
    order: 2,
  },
  {
    subjectSlug: "state-pcs-portals",
    subjectName: "State PCS Resources",
    topicSlug: "official-links",
    topicTitle: "Official links",
    studyGoal: "STATE_PCS",
    title: "NCERT foundations",
    slug: "state-ncert",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary: "NCERT textbooks — core GS material for State PCS prelims and mains.",
    order: 3,
  },
];
