import type { PreloadedCatalogEntry } from "./types.js";

export const PRELOADED_CATALOG_GATE: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "gate-official",
    subjectName: "GATE Official",
    topicSlug: "exam-portal",
    topicTitle: "Exam portal",
    studyGoal: "GATE",
    title: "GATE 2026 — IIT Guwahati",
    slug: "gate-2026-iitg",
    sourceUrl: "https://gate2026.iitg.ac.in/",
    license: "LINK_ONLY",
    summary:
      "Official GATE conducting IIT website — brochure, syllabus, and exam notices.",
    order: 1,
  },
  {
    subjectSlug: "gate-official",
    subjectName: "GATE Official",
    topicSlug: "exam-portal",
    topicTitle: "Exam portal",
    studyGoal: "GATE",
    title: "NPTEL — IIT course portal",
    slug: "nptel-courses",
    sourceUrl: "https://nptel.ac.in/",
    license: "LINK_ONLY",
    summary:
      "Government-funded NPTEL video courses and notes for engineering GATE subjects.",
    order: 2,
  },
  {
    subjectSlug: "gate-official",
    subjectName: "GATE Official",
    topicSlug: "exam-portal",
    topicTitle: "Exam portal",
    studyGoal: "GATE",
    title: "NCERT science foundations",
    slug: "gate-ncert-science",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary: "NCERT science textbooks useful for GATE XL and general aptitude.",
    order: 3,
  },
];

export const PRELOADED_CATALOG_CA: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "ICAI — Institute of Chartered Accountants",
    slug: "icai-home",
    sourceUrl: "https://www.icai.org/",
    license: "LINK_ONLY",
    summary:
      "Official ICAI portal — announcements, exam schedules, and standards.",
    order: 1,
  },
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "Ministry of Corporate Affairs",
    slug: "mca-gov",
    sourceUrl: "https://www.mca.gov.in/",
    license: "LINK_ONLY",
    summary: "Companies Act, LLP rules, and corporate law notifications from MCA.",
    order: 2,
  },
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "Income Tax Department",
    slug: "income-tax-portal",
    sourceUrl: "https://www.incometax.gov.in/",
    license: "LINK_ONLY",
    summary: "Official income tax portal — rules, circulars, and taxpayer services.",
    order: 3,
  },
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "GST portal",
    slug: "gst-official",
    sourceUrl: "https://www.gst.gov.in/",
    license: "LINK_ONLY",
    summary: "Official GST portal — indirect tax updates and compliance resources.",
    order: 4,
  },
  {
    subjectSlug: "ca-official",
    subjectName: "CA Official",
    topicSlug: "institute-portals",
    topicTitle: "Institute portals",
    studyGoal: "CA",
    title: "Union Budget — CA relevance",
    slug: "ca-budget-portal",
    sourceUrl: "https://www.indiabudget.gov.in/",
    license: "OFFICIAL_DOCUMENT",
    summary: "Official budget documents for taxation and fiscal policy questions.",
    order: 5,
  },
];

export const PRELOADED_CATALOG_NEET: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "regulatory",
    topicTitle: "Regulatory bodies",
    studyGoal: "NEET_PG",
    title: "National Medical Commission",
    slug: "nmc-official",
    sourceUrl: "https://www.nmc.org.in/",
    license: "LINK_ONLY",
    summary:
      "Official NMC portal — medical education standards and notifications.",
    order: 1,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "regulatory",
    topicTitle: "Regulatory bodies",
    studyGoal: "NEET_PG",
    title: "National Board of Examinations",
    slug: "nbe-official",
    sourceUrl: "https://natboard.edu.in/",
    license: "LINK_ONLY",
    summary:
      "Official NBE site — NEET-PG, FMGE, and postgraduate exam information.",
    order: 2,
  },
  {
    subjectSlug: "medicine-official",
    subjectName: "Medicine Official",
    topicSlug: "regulatory",
    topicTitle: "Regulatory bodies",
    studyGoal: "NEET_PG",
    title: "NCERT biology textbooks",
    slug: "neet-ncert-biology",
    sourceUrl: "https://ncert.nic.in/textbook.php",
    license: "OFFICIAL_DOCUMENT",
    summary: "Official NCERT biology textbooks — preclinical foundations for NEET-PG.",
    order: 3,
  },
];

export const PRELOADED_CATALOG_JUDICIARY: PreloadedCatalogEntry[] = [
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "India Code — Bare Acts",
    slug: "judiciary-india-code",
    sourceUrl: "https://www.indiacode.nic.in/",
    license: "LINK_ONLY",
    summary:
      "Authoritative bare acts for judiciary and judicial services preparation.",
    order: 1,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "Supreme Court of India",
    slug: "supreme-court-india",
    sourceUrl: "https://main.sci.gov.in/",
    license: "LINK_ONLY",
    summary:
      "Official Supreme Court portal — judgments, cause lists, and circulars.",
    order: 2,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "Law Commission of India",
    slug: "law-commission",
    sourceUrl: "https://lawcommissionofindia.nic.in/",
    license: "LINK_ONLY",
    summary:
      "Official Law Commission reports and consultation papers on legal reform.",
    order: 3,
  },
  {
    subjectSlug: "law-official",
    subjectName: "Law Official",
    topicSlug: "statutes",
    topicTitle: "Statutes & courts",
    studyGoal: "JUDICIARY",
    title: "eGazette — statutory notifications",
    slug: "judiciary-egazette",
    sourceUrl: "https://egazette.gov.in/",
    license: "LINK_ONLY",
    summary: "Central gazette for new acts, rules, and amendments.",
    order: 4,
  },
];
